/**
 * Create Onboarding Lead Use Case
 */

import { CreateUseCaseTemplate } from '@oxlayer/snippets/use-cases';
import type { AppResult } from '@oxlayer/snippets/use-cases';
import type { OnboardingLeadRepository } from '@/repositories/index.js';
import type { EventBus } from '@oxlayer/capabilities-events';
import { OnboardingLeadEntity, OnboardingLeadCreatedEvent } from '@/domain/index.js';

export interface CreateOnboardingLeadInput {
  userType: 'provider' | 'company';
  categoryId?: number;
  establishmentTypeId?: number;
  document: string;
  email?: string;
  name?: string;
  phone: string;
  termsAccepted: boolean;
  privacyAccepted: boolean;
  notes?: string;
  metadata?: Record<string, unknown>;
}

export interface CreateOnboardingLeadOutput {
  id: number;
  userType: string;
  categoryId: number | null;
  establishmentTypeId: number | null;
  document: string;
  email: string;
  name: string | null;
  phone: string;
  status: string;
  createdAt: Date;
}

export class CreateOnboardingLeadUseCase extends CreateUseCaseTemplate<
  CreateOnboardingLeadInput,
  OnboardingLeadEntity,
  AppResult<CreateOnboardingLeadOutput & Record<string, unknown>>
> {
  private repository: OnboardingLeadRepository;

  constructor(
    onboardingLeadRepository: OnboardingLeadRepository,
    eventBus: EventBus,
    _domainEvents: unknown,
    _businessMetrics: unknown,
    tracer?: unknown | null
  ) {
    super({
      generateId: () => '', // ID will be generated by database
      createEntity: (data) => OnboardingLeadEntity.create(data),
      persistEntity: async (entity) => {
        // Don't use return value here (template expects void)
        await onboardingLeadRepository.create(entity);
      },
      publishEvent: async (event) => {
        try {
          await eventBus.emit(event);
        } catch (error) {
          console.warn('Failed to publish event:', error);
        }
      },
      recordMetric: async (_name, _value) => {
        // Metrics recording is optional - no-op if not configured
      },
      toOutput: (entity) => ({
        id: entity.id,
        userType: entity.userType,
        categoryId: entity.categoryId,
        establishmentTypeId: entity.establishmentTypeId,
        document: entity.document,
        email: entity.email,
        name: entity.name,
        phone: entity.phone,
        status: entity.status,
        createdAt: entity.createdAt,
      }),
      tracer,
    });
    this.repository = onboardingLeadRepository;
  }

  /**
   * Override execute to use the returned entity from persistEntity
   * which has the database-generated id
   */
  async execute(input: CreateOnboardingLeadInput): Promise<AppResult<CreateOnboardingLeadOutput & Record<string, unknown>>> {
    // 1. Create entity with id: 0 (will be replaced by database)
    const entity = OnboardingLeadEntity.create(input);

    // 2. Persist to database and get entity with generated id
    const persistedEntity = await this.repository.create(entity);

    // 3. Publish event (skip if event creation fails or returns null)
    try {
      const event = this.createEvent(persistedEntity, String(persistedEntity.id));
      await (this.dependencies as any).publishEvent(event);
    } catch (error) {
      console.warn('Failed to create/publish event:', error);
    }

    // 4. Record metric
    await (this.dependencies as any).recordMetric('onboarding_lead.created', 1);

    // 5. Return output with the persisted entity
    const output = (this.dependencies as any).toOutput(persistedEntity);
    return {
      success: true,
      data: output as CreateOnboardingLeadOutput & Record<string, unknown>,
    };
  }

  protected override createEvent(entity: OnboardingLeadEntity, _id: string): OnboardingLeadCreatedEvent {
    return new OnboardingLeadCreatedEvent(entity.id, {
      userType: entity.userType,
      email: entity.email ?? '',
      phone: entity.phone,
    });
  }
}
