/**
 * Create Onboarding Lead Use Case
 */

import { CreateUseCaseTemplate } from '@oxlayer/snippets/use-cases';
import { OnboardingLeadRepository } from '@/repositories/index.js';
import { EventBus } from '@oxlayer/capabilities-events';
import { OnboardingLeadEntity, OnboardingLeadCreatedEvent } from '@/domain/index.js';

export interface CreateOnboardingLeadInput {
  userType: 'provider' | 'company';
  categoryId?: number;
  establishmentTypeId?: number;
  document: string;
  email: string;
  name?: string;
  phone: string;
  termsAccepted: boolean;
  privacyAccepted: boolean;
  notes?: string;
  metadata?: Record<string, unknown>;
}

export interface CreateOnboardingLeadOutput {
  id: number;
  userType: string;
  email: string;
  phone: string;
  status: string;
  createdAt: Date;
}

export class CreateOnboardingLeadUseCase extends CreateUseCaseTemplate<
  CreateOnboardingLeadInput,
  OnboardingLeadEntity,
  Promise<CreateOnboardingLeadOutput>
> {
  constructor(
    private onboardingLeadRepository: OnboardingLeadRepository,
    eventBus: EventBus,
    tracer?: unknown | null
  ) {
    super({
      generateId: () => 0, // ID will be generated by database
      createEntity: (data) => OnboardingLeadEntity.create(data),
      persistEntity: async (entity) => {
        return await onboardingLeadRepository.create(entity);
      },
      publishEvent: async (event) => {
        try {
          await eventBus.emit(event);
        } catch (error) {
          console.warn('Failed to publish event:', error);
        }
      },
      toOutput: (entity) => ({
        id: entity.id,
        userType: entity.userType,
        email: entity.email,
        phone: entity.phone,
        status: entity.status,
        createdAt: entity.createdAt,
      }),
      tracer,
    });
  }

  protected override createEvent(entity: OnboardingLeadEntity, _id: number): OnboardingLeadCreatedEvent {
    return new OnboardingLeadCreatedEvent(entity.id, {
      userType: entity.userType,
      email: entity.email,
      phone: entity.phone,
    });
  }
}
