packages:
  # Apps workspaces
  - 'apps/**'

  # Frontend workspaces
  - 'frontend/**'

  # Backend workspaces
  - 'backend/**'
  - '!backend/release/**'

  # CLI packages
  - 'cli/**'

  # MCP packages
  - 'mcp_oxlayer/**'