packages:
    - "internal"
    - "auth"
    - "cache"
    - "docs"
    - "events"
    - "metrics"
    - "queues"
    - "scheduler"
    - "search"
    - "telemetry"
    - "telemetry/**/*"
    - "tenancy"
    - "vector"
    - "adapters/**/*"