-- Seed script for establishment types
-- Each type has flags indicating which fields are required

INSERT INTO establishment_types (name, description, requires_delivery, requires_location, requires_menu, requires_hours) VALUES
('Restaurante', NULL, TRUE, TRUE, TRUE, TRUE),
('Padaria', NULL, TRUE, TRUE, TRUE, TRUE),
('Farmácia', NULL, FALSE, TRUE, TRUE, TRUE),
('Posto de Gasolina', NULL, FALSE, TRUE, FALSE, TRUE),
('Distribuidora de Bebidas', NULL, TRUE, TRUE, TRUE, FALSE),
('Distribuidora de Água e Gás', NULL, TRUE, TRUE, FALSE, FALSE),
('Loja de Colchão', NULL, TRUE, TRUE, TRUE, FALSE),
('Loja de Móveis', NULL, TRUE, TRUE, TRUE, FALSE),
('Contador', NULL, FALSE, FALSE, FALSE, FALSE),
('Advogado', NULL, FALSE, FALSE, FALSE, FALSE),
('Médico', NULL, FALSE, TRUE, FALSE, TRUE),
('Contabilidade', NULL, FALSE, FALSE, FALSE, FALSE),
('Escritório de Advocacia', NULL, FALSE, FALSE, FALSE, FALSE),
('Ótica', NULL, FALSE, TRUE, TRUE, TRUE),
('Papelaria', NULL, FALSE, TRUE, TRUE, TRUE),
('Supermercado', NULL, TRUE, TRUE, TRUE, TRUE),
('Mercado', NULL, TRUE, TRUE, TRUE, TRUE),
('Lanchonete', NULL, TRUE, TRUE, TRUE, TRUE),
('Pizzaria', NULL, TRUE, TRUE, TRUE, TRUE),
('Hamburgueria', NULL, TRUE, TRUE, TRUE, TRUE),
('Açougue', NULL, TRUE, TRUE, TRUE, TRUE),
('Peixaria', NULL, TRUE, TRUE, TRUE, TRUE),
('Hortifruti', NULL, TRUE, TRUE, TRUE, TRUE),
('Livraria', NULL, FALSE, TRUE, TRUE, TRUE),
('Eletrônicos', NULL, TRUE, TRUE, TRUE, TRUE),
('Loja de Roupas', NULL, TRUE, TRUE, TRUE, TRUE),
('Sapataria', NULL, TRUE, TRUE, TRUE, TRUE),
('Barbearia', NULL, FALSE, TRUE, FALSE, TRUE),
('Salão de Beleza', NULL, FALSE, TRUE, FALSE, TRUE),
('Clínica de Estética', NULL, FALSE, TRUE, FALSE, TRUE),
('Oficina Mecânica', NULL, FALSE, TRUE, FALSE, TRUE),
('Auto Elétrica', NULL, FALSE, TRUE, FALSE, TRUE),
('Funilaria e Pintura', NULL, FALSE, TRUE, FALSE, TRUE),
('Lavanderia', NULL, TRUE, TRUE, FALSE, TRUE),
('Lava Jato', NULL, FALSE, TRUE, FALSE, TRUE),
('Pet Shop', NULL, FALSE, TRUE, TRUE, TRUE),
('Veterinário', NULL, FALSE, TRUE, FALSE, TRUE),
('Academia', NULL, FALSE, TRUE, FALSE, TRUE),
('Escola', NULL, FALSE, TRUE, FALSE, TRUE),
('Creche', NULL, FALSE, TRUE, FALSE, TRUE),
('Hotel', NULL, FALSE, TRUE, FALSE, TRUE),
('Pousada', NULL, FALSE, TRUE, FALSE, TRUE),
('Boate', NULL, FALSE, TRUE, TRUE, TRUE),
('Bar', NULL, FALSE, TRUE, TRUE, TRUE),
('Pub', NULL, FALSE, TRUE, TRUE, TRUE),
('Café', NULL, FALSE, TRUE, TRUE, TRUE),
('Sorveteria', NULL, FALSE, TRUE, TRUE, TRUE),
('Doceria', NULL, FALSE, TRUE, TRUE, TRUE),
('Chocolataria', NULL, FALSE, TRUE, TRUE, TRUE),
('Confeitaria', NULL, FALSE, TRUE, TRUE, TRUE),
('Floricultura', NULL, TRUE, TRUE, TRUE, TRUE),
('Jardinagem', NULL, TRUE, TRUE, FALSE, FALSE),
('Marcenaria', NULL, TRUE, TRUE, FALSE, FALSE),
('Serralheria', NULL, TRUE, TRUE, FALSE, FALSE),
('Material de Construção', NULL, TRUE, TRUE, TRUE, FALSE),
('Tintas', NULL, TRUE, TRUE, TRUE, FALSE),
('Loja de Móveis de Escritório', NULL, TRUE, TRUE, TRUE, FALSE),
('Informática', NULL, TRUE, TRUE, TRUE, TRUE),
('Telefonia', NULL, TRUE, TRUE, TRUE, TRUE),
('Jogos e Brinquedos', NULL, TRUE, TRUE, TRUE, TRUE),
('Loja de Presentes', NULL, TRUE, TRUE, TRUE, TRUE),
('Bijuterias', NULL, TRUE, TRUE, TRUE, TRUE),
('Joalheria', NULL, TRUE, TRUE, TRUE, TRUE),
('Perfumaria', NULL, TRUE, TRUE, TRUE, TRUE),
('Cosméticos', NULL, TRUE, TRUE, TRUE, TRUE),
('Boutique', NULL, TRUE, TRUE, TRUE, TRUE),
('Lingerie', NULL, TRUE, TRUE, TRUE, TRUE),
('Loja de Calçados', NULL, TRUE, TRUE, TRUE, TRUE),
('Bolsas e Acessórios', NULL, TRUE, TRUE, TRUE, TRUE),
('Cama Mesa e Banho', NULL, TRUE, TRUE, TRUE, TRUE),
('Decoração', NULL, TRUE, TRUE, TRUE, TRUE),
('Artigos de Casa', NULL, TRUE, TRUE, TRUE, TRUE),
('Eletrodomésticos', NULL, TRUE, TRUE, TRUE, TRUE),
('Móveis Planejados', NULL, TRUE, TRUE, TRUE, FALSE),
('Cozinha Planejada', NULL, TRUE, TRUE, TRUE, FALSE);