-- Seed script for service provider categories
-- Generated from categories.csv

INSERT INTO service_provider_categories (created_at, updated_at, name, description) VALUES
(NOW(), NOW(), 'Higienização e Polimento', NULL),
(NOW(), NOW(), 'Tapeceiro', NULL),
(NOW(), NOW(), 'Confeiteira', NULL),
(NOW(), NOW(), 'Antenista', NULL),
(NOW(), NOW(), 'Toldos e Coberturas', NULL),
(NOW(), NOW(), 'Borracharia', NULL),
(NOW(), NOW(), 'Limpeza pós obra', NULL),
(NOW(), NOW(), 'Segurança Particular', NULL),
(NOW(), NOW(), 'Bandas e cantores', NULL),
(NOW(), NOW(), 'Auxílio administrativo', NULL),
(NOW(), NOW(), 'Produção de Conteúdo', NULL),
(NOW(), NOW(), 'Áudio e Vídeo', NULL),
(NOW(), NOW(), 'DVD / Blu-Ray', NULL),
(NOW(), NOW(), 'Entregador', NULL),
(NOW(), NOW(), 'Podólogo', NULL),
(NOW(), NOW(), 'Edição de vídeos', NULL),
(NOW(), NOW(), 'Fogão e Cooktop', NULL),
(NOW(), NOW(), 'Limpeza e Higienização de Estofados', NULL),
(NOW(), NOW(), 'Impermeabilizador', NULL),
(NOW(), NOW(), 'Assessor de eventos', NULL),
(NOW(), NOW(), 'Corte e costura', NULL),
(NOW(), NOW(), 'Micropigmentador', NULL),
(NOW(), NOW(), 'Administração de Imóveis', NULL),
(NOW(), NOW(), 'Doula', NULL),
(NOW(), NOW(), 'Decorador', NULL),
(NOW(), NOW(), 'Chocolateiro', NULL),
(NOW(), NOW(), 'Motorista', NULL),
(NOW(), NOW(), 'Aluguel de maquinário', NULL),
(NOW(), NOW(), 'DJs', NULL),
(NOW(), NOW(), 'Adega Climatizada', NULL),
(NOW(), NOW(), 'Poço Artesiano', NULL),
(NOW(), NOW(), 'Venda de Automóveis', NULL),
(NOW(), NOW(), 'Lazer', NULL),
(NOW(), NOW(), 'Video Game', NULL),
(NOW(), NOW(), 'Lava Jato', NULL),
(NOW(), NOW(), 'Buffet completo', NULL),
(NOW(), NOW(), 'Gás', NULL),
(NOW(), NOW(), 'Bronzeamento', NULL),
(NOW(), NOW(), 'Máquina de Lavar', NULL),
(NOW(), NOW(), 'Eletricista', NULL),
(NOW(), NOW(), 'Engenheiro', NULL),
(NOW(), NOW(), 'Pesquisa em Geral', NULL),
(NOW(), NOW(), 'Automação residencial', NULL),
(NOW(), NOW(), 'Piscina', NULL),
(NOW(), NOW(), 'Convites', NULL),
(NOW(), NOW(), 'Economia e Finanças', NULL),
(NOW(), NOW(), 'Martelinho de Ouro', NULL),
(NOW(), NOW(), 'Encanador', NULL),
(NOW(), NOW(), 'Impermeabilização de Estofados e Tecidos', NULL),
(NOW(), NOW(), 'Diagramador', NULL),
(NOW(), NOW(), 'Barbeiros', NULL),
(NOW(), NOW(), 'Animação de festas', NULL),
(NOW(), NOW(), 'Arquitetos', NULL),
(NOW(), NOW(), 'Notebook', NULL),
(NOW(), NOW(), 'Saúde', NULL),
(NOW(), NOW(), 'Informática', NULL),
(NOW(), NOW(), 'Celebrantes', NULL),
(NOW(), NOW(), 'Bem-Estar', NULL),
(NOW(), NOW(), 'Cozinheira', NULL),
(NOW(), NOW(), 'Beleza', NULL),
(NOW(), NOW(), 'Recrutamento e Seleção', NULL),
(NOW(), NOW(), 'Médico', NULL),
(NOW(), NOW(), 'Redes de Proteção', NULL),
(NOW(), NOW(), 'Desentupidor', NULL),
(NOW(), NOW(), 'Serviços para Pets', NULL),
(NOW(), NOW(), 'Tapeceiro', NULL),
(NOW(), NOW(), 'Aquecedor a Gás', NULL),
(NOW(), NOW(), 'Lavagem de Tapetes', NULL),
(NOW(), NOW(), 'Telefone Fixo', NULL),
(NOW(), NOW(), 'Fisioterapeuta', NULL),
(NOW(), NOW(), 'UI design', NULL),
(NOW(), NOW(), 'Diarista', NULL),
(NOW(), NOW(), 'Cuidador de Pessoas', NULL),
(NOW(), NOW(), 'Equipamento para festas', NULL),
(NOW(), NOW(), 'Segurança do trabalho', NULL),
(NOW(), NOW(), 'Ensino Superior', NULL),
(NOW(), NOW(), 'Geladeira e Freezer', NULL),
(NOW(), NOW(), 'Edição de fotos', NULL),
(NOW(), NOW(), 'Vidraceiro', NULL),
(NOW(), NOW(), 'Montador de Móveis', NULL),
(NOW(), NOW(), 'Psicanalista', NULL),
(NOW(), NOW(), 'Paisagista', NULL),
(NOW(), NOW(), 'Coifas e Exaustores', NULL),
(NOW(), NOW(), 'Ilustração', NULL),
(NOW(), NOW(), 'Desenvolvimento de sites', NULL),
(NOW(), NOW(), 'Cabeleireiros', NULL),
(NOW(), NOW(), 'Babá', NULL),
(NOW(), NOW(), 'Alfaiate', NULL),
(NOW(), NOW(), 'Ensino Profissionalizante', NULL),
(NOW(), NOW(), 'Dentista', NULL),
(NOW(), NOW(), 'Empreiteiro', NULL),
(NOW(), NOW(), 'Música', NULL),
(NOW(), NOW(), 'Carros de casamento', NULL),
(NOW(), NOW(), 'Dedetizador', NULL),
(NOW(), NOW(), 'Web Design', NULL),
(NOW(), NOW(), 'Corretor', NULL),
(NOW(), NOW(), 'Passadeira', NULL),
(NOW(), NOW(), 'Artesanato', NULL),
(NOW(), NOW(), 'Advogado', NULL),
(NOW(), NOW(), 'Secadora de Roupas', NULL),
(NOW(), NOW(), 'Tradutores', NULL),
(NOW(), NOW(), 'Nutricionista', NULL),
(NOW(), NOW(), 'Fotografia', NULL),
(NOW(), NOW(), 'Personal stylist', NULL),
(NOW(), NOW(), 'Terapia Ocupacional', NULL),
(NOW(), NOW(), 'Cabeamento e Redes', NULL),
(NOW(), NOW(), 'Escrita e Conteúdo', NULL),
(NOW(), NOW(), 'Mediação de Conflitos', NULL),
(NOW(), NOW(), 'Local para eventos', NULL),
(NOW(), NOW(), 'Chaveiro', NULL),
(NOW(), NOW(), 'Garçons e copeiras', NULL),
(NOW(), NOW(), 'Marceneiro', NULL),
(NOW(), NOW(), 'Personal shopper', NULL),
(NOW(), NOW(), 'Jardinagem', NULL),
(NOW(), NOW(), 'TV e Teatro', NULL),
(NOW(), NOW(), 'Criação de marcas', NULL),
(NOW(), NOW(), 'Gesso e drywall', NULL),
(NOW(), NOW(), 'Desinfecção', NULL),
(NOW(), NOW(), 'Circo', NULL),
(NOW(), NOW(), 'Desenvolvimento Web', NULL),
(NOW(), NOW(), 'Animação motion', NULL),
(NOW(), NOW(), 'Instalador de Papel de Parede', NULL),
(NOW(), NOW(), 'Decoração', NULL),
(NOW(), NOW(), 'Apps para smartphone', NULL),
(NOW(), NOW(), 'Marmoraria e Granitos', NULL),
(NOW(), NOW(), 'Biomedicina Estética', NULL),
(NOW(), NOW(), 'Produção gráfica', NULL),
(NOW(), NOW(), 'Depilação', NULL),
(NOW(), NOW(), 'Fone de Ouvido', NULL),
(NOW(), NOW(), 'Marido de Aluguel', NULL),
(NOW(), NOW(), 'Modelagem 2D e 3D', NULL),
(NOW(), NOW(), 'Instalação de eletrônicos', NULL),
(NOW(), NOW(), 'Máquina de Costura', NULL),
(NOW(), NOW(), 'Lava Louça', NULL),
(NOW(), NOW(), 'Consultor pessoal', NULL),
(NOW(), NOW(), 'Instalador TV Digital', NULL),
(NOW(), NOW(), 'Digitalizar documentos', NULL),
(NOW(), NOW(), 'Mecânica Geral', NULL),
(NOW(), NOW(), 'Materiais promocionais', NULL),
(NOW(), NOW(), 'Remoção de Entulho', NULL),
(NOW(), NOW(), 'Jogos', NULL),
(NOW(), NOW(), 'Organização de Eventos', NULL),
(NOW(), NOW(), 'Pavimentação', NULL),
(NOW(), NOW(), 'Psicólogo', NULL),
(NOW(), NOW(), 'Enfermeira', NULL),
(NOW(), NOW(), 'Guia de Turismo', NULL),
(NOW(), NOW(), 'Tablet', NULL),
(NOW(), NOW(), 'Educação Especial', NULL),
(NOW(), NOW(), 'Pedreiro', NULL),
(NOW(), NOW(), 'Dança', NULL),
(NOW(), NOW(), 'Televisão', NULL),
(NOW(), NOW(), 'Criação de logos', NULL),
(NOW(), NOW(), 'Alarme automotivo', NULL),
(NOW(), NOW(), 'Coach', NULL),
(NOW(), NOW(), 'Mudanças e Carretos', NULL),
(NOW(), NOW(), 'Paisagismo', NULL),
(NOW(), NOW(), 'Banheira', NULL),
(NOW(), NOW(), 'Moda', NULL),
(NOW(), NOW(), 'Moda', NULL),
(NOW(), NOW(), 'Fonoaudiólogo', NULL),
(NOW(), NOW(), 'Detetive particular', NULL),
(NOW(), NOW(), 'Concursos', NULL),
(NOW(), NOW(), 'Esportes', NULL),
(NOW(), NOW(), 'Ar Condicionado', NULL),
(NOW(), NOW(), 'Pintor', NULL),
(NOW(), NOW(), 'Despachante', NULL),
(NOW(), NOW(), 'Fotografia', NULL),
(NOW(), NOW(), 'Idiomas', NULL),
(NOW(), NOW(), 'Assessoria de Imprensa', NULL),
(NOW(), NOW(), 'Design de Interiores', NULL),
(NOW(), NOW(), 'Celular', NULL),
(NOW(), NOW(), 'Lavadeira', NULL),
(NOW(), NOW(), 'Impressora', NULL),
(NOW(), NOW(), 'Restauração de Fotos', NULL),
(NOW(), NOW(), 'Maquiadores', NULL),
(NOW(), NOW(), 'Tarefas', NULL),
(NOW(), NOW(), 'Esteticistas', NULL),
(NOW(), NOW(), 'Auto elétrico', NULL),
(NOW(), NOW(), 'Testamento e Planejamento Patrimonial', NULL),
(NOW(), NOW(), 'Desenvolvimento de games', NULL),
(NOW(), NOW(), 'Consultoria especializada', NULL),
(NOW(), NOW(), 'Visagista', NULL),
(NOW(), NOW(), 'Assessor de Investimentos', NULL),
(NOW(), NOW(), 'Câmera', NULL),
(NOW(), NOW(), 'Ar condicionado', NULL),
(NOW(), NOW(), 'Remoção de Tatuagem', NULL),
(NOW(), NOW(), 'Artes', NULL),
(NOW(), NOW(), 'Funilaria', NULL),
(NOW(), NOW(), 'Escolares e Reforço', NULL),
(NOW(), NOW(), 'Limpeza de Piscina', NULL),
(NOW(), NOW(), 'Esotérico', NULL),
(NOW(), NOW(), 'Pintura', NULL),
(NOW(), NOW(), 'Aparelho de Som', NULL),
(NOW(), NOW(), 'Brindes e lembrancinhas', NULL),
(NOW(), NOW(), 'Segurança eletrônica', NULL),
(NOW(), NOW(), 'Vidraçaria Automotiva', NULL),
(NOW(), NOW(), 'Passeador de Cães', NULL),
(NOW(), NOW(), 'Bartender', NULL),
(NOW(), NOW(), 'Terapias Alternativas', NULL),
(NOW(), NOW(), 'Recepcionistas', NULL),
(NOW(), NOW(), 'Luta', NULL),
(NOW(), NOW(), 'Convites', NULL),
(NOW(), NOW(), 'Estética Automotiva', NULL),
(NOW(), NOW(), 'Marketing digital', NULL),
(NOW(), NOW(), 'Aconselhamento Conjugal e Familiar', NULL),
(NOW(), NOW(), 'Designer de cílios', NULL),
(NOW(), NOW(), 'Personal Trainer', NULL),
(NOW(), NOW(), 'Quiropraxia', NULL),
(NOW(), NOW(), 'Adestrador de Cães', NULL),
(NOW(), NOW(), 'Som automotivo', NULL),
(NOW(), NOW(), 'Design de sobrancelhas', NULL),
(NOW(), NOW(), 'Serralheria e solda', NULL),
(NOW(), NOW(), 'Pré-Vestibular', NULL),
(NOW(), NOW(), 'Computador Desktop', NULL),
(NOW(), NOW(), 'Manicure e pedicure', NULL),
(NOW(), NOW(), 'Seguranças', NULL),
(NOW(), NOW(), 'Fotografia', NULL),
(NOW(), NOW(), 'Insulfilm', NULL),
(NOW(), NOW(), 'Manobrista', NULL),
(NOW(), NOW(), 'Marketing Digital', NULL),
(NOW(), NOW(), 'Microondas', NULL),
(NOW(), NOW(), 'Florista', NULL),
(NOW(), NOW(), 'Churrasqueiro', NULL),
(NOW(), NOW(), 'Home Theater', NULL),
(NOW(), NOW(), 'Personal Organizer', NULL),
(NOW(), NOW(), 'Esportes Eletrônicos', NULL),
(NOW(), NOW(), 'Telefonia PABX', NULL),
(NOW(), NOW(), 'Contador', NULL),
(NOW(), NOW(), 'Ônibus Balada', NULL),
(NOW(), NOW(), 'Capoteiro', NULL),
(NOW(), NOW(), 'Artesanato', NULL),
(NOW(), NOW(), 'Guincho', NULL),
(NOW(), NOW(), 'Sapateiro', NULL);