/**
 * Create User Use Case
 */

import { CreateUseCaseTemplate } from '@oxlayer/snippets/use-cases';
import { UserRepository } from '@/repositories/index.js';
import { EventBus } from '@oxlayer/capabilities-events';
import { UserEntity, UserCreatedEvent } from '@/domain/index.js';

export interface CreateUserInput {
  name: string;
  email: string;
  password: string;
  establishmentId?: number;
  role?: 'admin' | 'manager' | 'staff';
}

export interface CreateUserOutput {
  id: number;
  name: string;
  email: string;
  role: string;
  createdAt: Date;
}

export class CreateUserUseCase extends CreateUseCaseTemplate<
  CreateUserInput,
  UserEntity,
  Promise<CreateUserOutput>
> {
  constructor(
    private userRepository: UserRepository,
    eventBus: EventBus,
    tracer?: unknown | null
  ) {
    super({
      generateId: () => 0, // ID will be generated by database
      createEntity: (data) => UserEntity.create(data),
      persistEntity: async (entity) => {
        return await userRepository.create(entity);
      },
      publishEvent: async (event) => {
        try {
          await eventBus.emit(event);
        } catch (error) {
          console.warn('Failed to publish event:', error);
        }
      },
      toOutput: (entity) => ({
        id: entity.id,
        name: entity.name,
        email: entity.email,
        role: entity.role,
        createdAt: entity.createdAt,
      }),
      tracer,
    });
  }

  protected override createEvent(entity: UserEntity, _id: number): UserCreatedEvent {
    return new UserCreatedEvent(entity.id, {
      email: entity.email,
      name: entity.name,
    });
  }
}
