#!/usr/bin/env node

/**
 * Embed markdown files into a TypeScript file as string constants.
 * This makes the bundled MCP server completely standalone.
 */

import { readdirSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const DOCS_DIR = join(__dirname, '../docs');
const OUTPUT_FILE = join(__dirname, '../src/docs-embedded.ts');

// Read all markdown files from docs directory recursively
function walkDir(dir: string, baseDir: string = dir): { path: string; content: string }[] {
  const files: { path: string; content: string }[] = [];
  const entries = readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkDir(fullPath, baseDir));
    } else if (entry.name.endsWith('.md')) {
      const relativePath = fullPath.substring(baseDir.length + 1);
      const content = readFileSync(fullPath, 'utf-8');
      files.push({ path: relativePath, content });
    }
  }

  return files;
}

// Generate the embedded docs file
function generateEmbeddedDocs() {
  const files = walkDir(DOCS_DIR);

  const imports: string[] = [];
  const exports: string[] = [];

  for (const file of files) {
    const varName = file.path
      .replace(/[^a-zA-Z0-9]/g, '_')
      .replace(/_+/g, '_')
      .replace(/^_|_$/g, '');

    const escapedContent = JSON.stringify(file.content);

    exports.push(`  /** ${file.path} */`);
    exports.push(`  ${varName}: ${escapedContent},`);
  }

  const content = `// Auto-generated by scripts/embed-docs.ts
// DO NOT EDIT - This file is generated from the markdown files in docs/

export const embeddedDocs: Record<string, string> = {
${exports.join('\n')}
};
`;

  // Write to src/docs-embedded.ts
  import('fs/promises').then(({ writeFile }) => {
    writeFile(OUTPUT_FILE, content, 'utf-8')
      .then(() => {
        console.log(`✅ Embedded ${files.length} markdown files into ${OUTPUT_FILE}`);
        files.forEach(f => console.log(`   - ${f.path}`));
      })
      .catch(console.error);
  });
}

generateEmbeddedDocs();
