/**
 * Post-Install Hooks System
 *
 * Allows SDK packages to run setup code after installation
 */

import { promises as fs } from 'fs';
import { join } from 'path';
import { existsSync } from 'fs';

/**
 * Post-install context provided to hooks
 */
export interface PostInstallContext {
  version: string;
  vendorDir: string;
  projectRoot: string;
  projectType: string;
  packageManager: string;
  capabilities: Record<string, unknown>;
}

/**
 * Post-install hook function signature
 */
export type PostInstallHook = (context: PostInstallContext) => Promise<void> | void;

/**
 * Hook result
 */
export interface HookResult {
  hookName: string;
  status: 'success' | 'warning' | 'error';
  message: string;
  output?: string;
}

/**
 * Hook definition in package.json
 */
export interface HookDefinition {
  file: string;
  run?: string;
}

/**
 * Execute post-install hooks for a given version
 */
export async function executeHooks(context: PostInstallContext): Promise<HookResult[]> {
  const results: HookResult[] = [];

  // Find all hook files
  const hooksDir = join(context.vendorDir, 'hooks');
  if (!existsSync(hooksDir)) {
    return results;
  }

  const hookFiles = await fs.readdir(hooksDir).filter(f => f.endsWith('.js') || f.endsWith('.mjs'));

  for (const hookFile of hookFiles) {
    const hookPath = join(hooksDir, hookFile);
    const hookName = hookFile.replace(/\.(js|mjs)$/, '');

    try {
      // Clear require cache to ensure fresh execution
      delete require.cache[require.resolve(hookPath)];

      // Load and execute hook
      const hook: PostInstallHook = (await import(hookPath)).default || (await import(hookPath)).postInstall;

      if (typeof hook === 'function') {
        await hook(context);
        results.push({
          hookName,
          status: 'success',
          message: 'Hook executed successfully',
        });
      } else {
        results.push({
          hookName,
          status: 'warning',
          message: 'No default export or postInstall function found',
        });
      }
    } catch (err) {
      results.push({
        hookName,
        status: 'error',
        message: err instanceof Error ? err.message : 'Unknown error',
      });
    }
  }

  return results;
}

/**
 * Create a post-install hook file template
 */
export async function createHookTemplate(
  hookName: string,
  vendorDir: string
): Promise<void> {
  const hooksDir = join(vendorDir, 'hooks');
  await fs.mkdir(hooksDir, { recursive: true });

  const hookPath = join(hooksDir, `${hookName}.js`);

  const template = `/**
 * ${hookName} Post-Install Hook
 *
 * This hook runs after SDK installation.
 * Use it to set up configuration, generate files, or validate environment.
 */

export default async function postInstall(context) {
  const { version, projectRoot, capabilities } = context;

  console.log(\`Running post-install for SDK \${version}...\`);

  // Example: Add environment variables to .env
  // const { appendFileSync } = await import('fs');
  // const envPath = require('path').join(projectRoot, '.env');
  // appendFileSync(envPath, \`
  // # OxLayer SDK
  // OXLAYER_SDK_VERSION=\${version}
  // \`);

  // Example: Generate config file
  // const { writeFileSync } = await import('fs');
  // const { join } = await import('path');
  // const configPath = join(projectRoot, 'oxlayer.config.json');
  // writeFileSync(configPath, JSON.stringify({
  //   version,
  //   capabilities: Object.keys(capabilities),
  // }, null, 2));

  console.log('Post-install complete!');
}

export const hookName = '${hookName}';
export const hookVersion = '1.0.0';
`;

  await fs.writeFile(hookPath, template);
}

/**
 * Built-in post-install hooks
 */

/**
 * Hook: Generate .env file with SDK configuration
 */
export async function generateEnvHook(context: PostInstallContext): Promise<void> {
  const envPath = join(context.projectRoot, '.env');

  // Check if .env exists
  if (!existsSync(envPath)) {
    const envContent = `
# OxLayer SDK Configuration
# Generated by SDK installer
OXLAYER_SDK_VERSION=${context.version}
OXLAYER_VENDOR_DIR=.capabilities-vendor/${context.version}
`;

    await fs.writeFile(envPath, envContent.trim());
  }
}

/**
 * Hook: Update tsconfig.json paths
 */
export async function updateTsconfigPathsHook(context: PostInstallContext): Promise<void> {
  const tsconfigPath = join(context.projectRoot, 'tsconfig.json');

  if (!existsSync(tsconfigPath)) {
    return;
  }

  const tsconfig = JSON.parse(await fs.readFile(tsconfigPath, 'utf-8'));

  // Add paths for vendor directory
  if (!tsconfig.compilerOptions) {
    tsconfig.compilerOptions = {};
  }

  if (!tsconfig.compilerOptions.paths) {
    tsconfig.compilerOptions.paths = {};
  }

  // Add path mapping for SDK packages
  const vendorPath = `.capabilities-vendor/${context.version}`;
  tsconfig.compilerOptions.paths['@oxlayer/*'] = [`${vendorPath}/*`];

  await fs.writeFile(tsconfigPath, JSON.stringify(tsconfig, null, 2));
}

/**
 * Hook: Print capability warnings
 */
export async function printCapabilityWarningsHook(context: PostInstallContext): Promise<void> {
  const { capabilities } = context;

  // Check for specific capability limits and warn if needed
  for (const [capability, limits] of Object.entries(capabilities)) {
    if (typeof limits === 'object' && limits !== null) {
      if ('maxRealms' in limits && (limits as any).maxRealms === 1) {
        console.warn(`⚠️  Warning: Limited to 1 realm for ${capability}`);
      }
      if ('maxStorageGb' in limits && (limits as any).maxStorageGb < 100) {
        console.warn(`⚠️  Warning: Limited to ${(limits as any).maxStorageGb}GB storage for ${capability}`);
      }
    }
  }
}

/**
 * Execute built-in hooks
 */
export async function executeBuiltinHooks(context: PostInstallContext): Promise<void> {
  await generateEnvHook(context);
  await updateTsconfigPathsHook(context);
  await printCapabilityWarningsHook(context);
}

export default {
  executeHooks,
  createHookTemplate,
  executeBuiltinHooks,
};
