{
 "title": "Quickwit Indexers",
 "tags": [
  "quickwit",
  "indexer"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(quickwit_memory_in_flight_data_bytes, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Indexing throughput",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(docs_processed_status) (rate(quickwit_indexing_processed_bytes{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{docs_processed_status}}"
    }
   ]
  },
  {
   "title": "Documents throughput",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "suffix: docs/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(docs_processed_status) (rate(quickwit_indexing_processed_docs_total{instance=~\"$pod|$instance\"}[$__rate_interval]))",
     "legendFormat": "{{docs_processed_status}}"
    }
   ]
  },
  {
   "title": "Indexing throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(docs_processed_status, index) (rate(quickwit_indexing_processed_bytes{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{docs_processed_status}}-{{index}}"
    }
   ]
  },
  {
   "title": "Writes rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(quickwit_write_bytes{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} {{component}}"
    }
   ]
  },
  {
   "title": "Memory usage (allocated and RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "quickwit_memory_allocated_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} allocated"
    },
    {
     "expr": "quickwit_memory_resident_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} RSS"
    }
   ]
  },
  {
   "title": "Merge operations (ongoing and pending)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "quickwit_indexing_ongoing_merge_operations{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} ongoing"
    },
    {
     "expr": "quickwit_indexing_pending_merge_operations{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} pending"
    }
   ]
  },
  {
   "title": "Object storage transfer rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(quickwit_storage_object_storage_download_num_bytes{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Download bytes / sec - {{pod}}"
    },
    {
     "expr": "sum by(pod) (rate(quickwit_storage_object_storage_upload_num_bytes{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Upload bytes / sec - {{pod}}"
    }
   ]
  },
  {
   "title": "Indexed documents rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(docs_processed_status, index) (rate(quickwit_indexing_processed_docs_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{docs_processed_status}}-{{index}}"
    }
   ]
  },
  {
   "title": "Requests on object storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(quickwit_storage_object_storage_gets_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "GET req/sec"
    },
    {
     "expr": "sum(rate(quickwit_storage_object_storage_puts_total{namespace=\"$namespace\", pod=~\"$pod\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "PUT req/sec"
    }
   ]
  },
  {
   "title": "Thread unpark duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.75, rate(quickwit_cli_thread_unpark_duration_microseconds_bucket{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Backpressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(quickwit_indexing_backpressure_micros{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{actor_name}}-{{pod}}"
    }
   ]
  }
 ]
}