/**
 * Create Establishment Use Case
 */

import { CreateUseCaseTemplate } from '@oxlayer/snippets/use-cases';
import type { AppResult } from '@oxlayer/snippets/use-cases';
import { EstablishmentRepository } from '@/repositories/index.js';
import { EventBus } from '@oxlayer/capabilities-events';
import { EstablishmentEntity, EstablishmentCreatedEvent } from '@/domain/index.js';

export interface CreateEstablishmentInput {
  name: string;
  horarioFuncionamento: string;
  description: string;
  ownerId: number;
  image?: string;
  primaryColor?: string;
  secondaryColor?: string;
  lat?: number;
  long?: number;
  locationString?: string;
  maxDistanceDelivery?: number;
  establishmentTypeId?: number;
  website?: string;
  whatsapp?: string;
  instagram?: string;
  googleBusinessUrl?: string;
}

export interface CreateEstablishmentOutput {
  id: number;
  name: string;
  createdAt: Date;
}

export class CreateEstablishmentUseCase extends CreateUseCaseTemplate<
  CreateEstablishmentInput,
  EstablishmentEntity,
  AppResult<CreateEstablishmentOutput>
> {
  constructor(
    private establishmentRepository: EstablishmentRepository,
    eventBus: EventBus,
    domainEvents: any,
    businessMetrics: any,
    tracer?: unknown | null
  ) {
    super({
      generateId: () => '', // ID will be generated by database
      createEntity: (data) => EstablishmentEntity.create(data),
      persistEntity: async (_entity) => {
        // Database create is handled separately
      },
      publishEvent: async (event) => {
        try {
          await eventBus.emit(event);
        } catch (error) {
          console.warn('Failed to publish event:', error);
        }
      },
      recordMetric: async (name, value) => {
        try {
          await businessMetrics?.recordMetric(name, value);
        } catch (error) {
          console.warn('Failed to record metric:', error);
        }
      },
      toOutput: (entity) => ({
        id: entity.id,
        name: entity.name,
        createdAt: entity.createdAt,
      }),
      tracer,
    });
  }

  protected override createEvent(entity: EstablishmentEntity, _id: string): EstablishmentCreatedEvent {
    return new EstablishmentCreatedEvent(entity.id, {
      ownerId: entity.ownerId,
      name: entity.name,
    });
  }
}
