/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  DeleteV1DevelopersIdMutationResponse,
  DeleteV1DevelopersIdPathParams,
  DeleteV1DevelopersId404,
} from "../gen/DeleteV1DevelopersId.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteV1DevelopersIdMutationKey = () =>
  [{ url: "/v1/developers/:id" }] as const;

export type DeleteV1DevelopersIdMutationKey = ReturnType<
  typeof deleteV1DevelopersIdMutationKey
>;

/**
 * {@link /v1/developers/:id}
 */
export async function deleteV1DevelopersId(
  id: DeleteV1DevelopersIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteV1DevelopersIdMutationResponse,
    ResponseErrorConfig<DeleteV1DevelopersId404>,
    unknown
  >({ method: "DELETE", url: `/v1/developers/${id}`, ...requestConfig });
  return res.data;
}

export function deleteV1DevelopersIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = deleteV1DevelopersIdMutationKey();
  return mutationOptions<
    DeleteV1DevelopersIdMutationResponse,
    ResponseErrorConfig<DeleteV1DevelopersId404>,
    { id: DeleteV1DevelopersIdPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteV1DevelopersId(id, config);
    },
  });
}

/**
 * {@link /v1/developers/:id}
 */
export function useDeleteV1DevelopersId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteV1DevelopersIdMutationResponse,
      ResponseErrorConfig<DeleteV1DevelopersId404>,
      { id: DeleteV1DevelopersIdPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteV1DevelopersIdMutationKey();

  const baseOptions = deleteV1DevelopersIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteV1DevelopersIdMutationResponse,
    ResponseErrorConfig<DeleteV1DevelopersId404>,
    { id: DeleteV1DevelopersIdPathParams["id"] },
    TContext
  >;

  return useMutation<
    DeleteV1DevelopersIdMutationResponse,
    ResponseErrorConfig<DeleteV1DevelopersId404>,
    { id: DeleteV1DevelopersIdPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteV1DevelopersIdMutationResponse,
    ResponseErrorConfig<DeleteV1DevelopersId404>,
    { id: DeleteV1DevelopersIdPathParams["id"] },
    TContext
  >;
}
