/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  DeleteV1LicensesIdPackagesPackagenameMutationResponse,
  DeleteV1LicensesIdPackagesPackagenamePathParams,
  DeleteV1LicensesIdPackagesPackagename404,
} from "../gen/DeleteV1LicensesIdPackagesPackagename.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteV1LicensesIdPackagesPackagenameMutationKey = () =>
  [{ url: "/v1/licenses/:id/packages/:packageName" }] as const;

export type DeleteV1LicensesIdPackagesPackagenameMutationKey = ReturnType<
  typeof deleteV1LicensesIdPackagesPackagenameMutationKey
>;

/**
 * {@link /v1/licenses/:id/packages/:packageName}
 */
export async function deleteV1LicensesIdPackagesPackagename(
  id: DeleteV1LicensesIdPackagesPackagenamePathParams["id"],
  packageName: DeleteV1LicensesIdPackagesPackagenamePathParams["packageName"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteV1LicensesIdPackagesPackagenameMutationResponse,
    ResponseErrorConfig<DeleteV1LicensesIdPackagesPackagename404>,
    unknown
  >({
    method: "DELETE",
    url: `/v1/licenses/${id}/packages/${packageName}`,
    ...requestConfig,
  });
  return res.data;
}

export function deleteV1LicensesIdPackagesPackagenameMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = deleteV1LicensesIdPackagesPackagenameMutationKey();
  return mutationOptions<
    DeleteV1LicensesIdPackagesPackagenameMutationResponse,
    ResponseErrorConfig<DeleteV1LicensesIdPackagesPackagename404>,
    {
      id: DeleteV1LicensesIdPackagesPackagenamePathParams["id"];
      packageName: DeleteV1LicensesIdPackagesPackagenamePathParams["packageName"];
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, packageName }) => {
      return deleteV1LicensesIdPackagesPackagename(id, packageName, config);
    },
  });
}

/**
 * {@link /v1/licenses/:id/packages/:packageName}
 */
export function useDeleteV1LicensesIdPackagesPackagename<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteV1LicensesIdPackagesPackagenameMutationResponse,
      ResponseErrorConfig<DeleteV1LicensesIdPackagesPackagename404>,
      {
        id: DeleteV1LicensesIdPackagesPackagenamePathParams["id"];
        packageName: DeleteV1LicensesIdPackagesPackagenamePathParams["packageName"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    deleteV1LicensesIdPackagesPackagenameMutationKey();

  const baseOptions = deleteV1LicensesIdPackagesPackagenameMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteV1LicensesIdPackagesPackagenameMutationResponse,
    ResponseErrorConfig<DeleteV1LicensesIdPackagesPackagename404>,
    {
      id: DeleteV1LicensesIdPackagesPackagenamePathParams["id"];
      packageName: DeleteV1LicensesIdPackagesPackagenamePathParams["packageName"];
    },
    TContext
  >;

  return useMutation<
    DeleteV1LicensesIdPackagesPackagenameMutationResponse,
    ResponseErrorConfig<DeleteV1LicensesIdPackagesPackagename404>,
    {
      id: DeleteV1LicensesIdPackagesPackagenamePathParams["id"];
      packageName: DeleteV1LicensesIdPackagesPackagenamePathParams["packageName"];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteV1LicensesIdPackagesPackagenameMutationResponse,
    ResponseErrorConfig<DeleteV1LicensesIdPackagesPackagename404>,
    {
      id: DeleteV1LicensesIdPackagesPackagenamePathParams["id"];
      packageName: DeleteV1LicensesIdPackagesPackagenamePathParams["packageName"];
    },
    TContext
  >;
}
