/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  DeleteV1LicensesIdMutationResponse,
  DeleteV1LicensesIdPathParams,
  DeleteV1LicensesId404,
} from "../gen/DeleteV1LicensesId.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteV1LicensesIdMutationKey = () =>
  [{ url: "/v1/licenses/:id" }] as const;

export type DeleteV1LicensesIdMutationKey = ReturnType<
  typeof deleteV1LicensesIdMutationKey
>;

/**
 * {@link /v1/licenses/:id}
 */
export async function deleteV1LicensesId(
  id: DeleteV1LicensesIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteV1LicensesIdMutationResponse,
    ResponseErrorConfig<DeleteV1LicensesId404>,
    unknown
  >({ method: "DELETE", url: `/v1/licenses/${id}`, ...requestConfig });
  return res.data;
}

export function deleteV1LicensesIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = deleteV1LicensesIdMutationKey();
  return mutationOptions<
    DeleteV1LicensesIdMutationResponse,
    ResponseErrorConfig<DeleteV1LicensesId404>,
    { id: DeleteV1LicensesIdPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteV1LicensesId(id, config);
    },
  });
}

/**
 * {@link /v1/licenses/:id}
 */
export function useDeleteV1LicensesId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteV1LicensesIdMutationResponse,
      ResponseErrorConfig<DeleteV1LicensesId404>,
      { id: DeleteV1LicensesIdPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteV1LicensesIdMutationKey();

  const baseOptions = deleteV1LicensesIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteV1LicensesIdMutationResponse,
    ResponseErrorConfig<DeleteV1LicensesId404>,
    { id: DeleteV1LicensesIdPathParams["id"] },
    TContext
  >;

  return useMutation<
    DeleteV1LicensesIdMutationResponse,
    ResponseErrorConfig<DeleteV1LicensesId404>,
    { id: DeleteV1LicensesIdPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteV1LicensesIdMutationResponse,
    ResponseErrorConfig<DeleteV1LicensesId404>,
    { id: DeleteV1LicensesIdPathParams["id"] },
    TContext
  >;
}
