/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  DeleteV1OrganizationsIdMutationResponse,
  DeleteV1OrganizationsIdPathParams,
  DeleteV1OrganizationsId404,
} from "../gen/DeleteV1OrganizationsId.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteV1OrganizationsIdMutationKey = () =>
  [{ url: "/v1/organizations/:id" }] as const;

export type DeleteV1OrganizationsIdMutationKey = ReturnType<
  typeof deleteV1OrganizationsIdMutationKey
>;

/**
 * {@link /v1/organizations/:id}
 */
export async function deleteV1OrganizationsId(
  id: DeleteV1OrganizationsIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteV1OrganizationsIdMutationResponse,
    ResponseErrorConfig<DeleteV1OrganizationsId404>,
    unknown
  >({ method: "DELETE", url: `/v1/organizations/${id}`, ...requestConfig });
  return res.data;
}

export function deleteV1OrganizationsIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = deleteV1OrganizationsIdMutationKey();
  return mutationOptions<
    DeleteV1OrganizationsIdMutationResponse,
    ResponseErrorConfig<DeleteV1OrganizationsId404>,
    { id: DeleteV1OrganizationsIdPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteV1OrganizationsId(id, config);
    },
  });
}

/**
 * {@link /v1/organizations/:id}
 */
export function useDeleteV1OrganizationsId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteV1OrganizationsIdMutationResponse,
      ResponseErrorConfig<DeleteV1OrganizationsId404>,
      { id: DeleteV1OrganizationsIdPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteV1OrganizationsIdMutationKey();

  const baseOptions = deleteV1OrganizationsIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteV1OrganizationsIdMutationResponse,
    ResponseErrorConfig<DeleteV1OrganizationsId404>,
    { id: DeleteV1OrganizationsIdPathParams["id"] },
    TContext
  >;

  return useMutation<
    DeleteV1OrganizationsIdMutationResponse,
    ResponseErrorConfig<DeleteV1OrganizationsId404>,
    { id: DeleteV1OrganizationsIdPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteV1OrganizationsIdMutationResponse,
    ResponseErrorConfig<DeleteV1OrganizationsId404>,
    { id: DeleteV1OrganizationsIdPathParams["id"] },
    TContext
  >;
}
