/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  DeleteV1LicensesIdPackagesPackageMutationResponse,
  DeleteV1LicensesIdPackagesPackagePathParams,
  DeleteV1LicensesIdPackagesPackage404,
} from "../gen/DeleteV1LicensesIdPackagesPackage.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteV1LicensesIdPackagesPackageMutationKey = () =>
  [{ url: "/v1/licenses/:id/packages/:package" }] as const;

export type DeleteV1LicensesIdPackagesPackageMutationKey = ReturnType<
  typeof deleteV1LicensesIdPackagesPackageMutationKey
>;

/**
 * {@link /v1/licenses/:id/packages/:package}
 */
export async function deleteV1LicensesIdPackagesPackage(
  id: DeleteV1LicensesIdPackagesPackagePathParams["id"],
  package: DeleteV1LicensesIdPackagesPackagePathParams["package"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteV1LicensesIdPackagesPackageMutationResponse,
    ResponseErrorConfig<DeleteV1LicensesIdPackagesPackage404>,
    unknown
  >({
    method: "DELETE",
    url: `/v1/licenses/${id}/packages/${package}`,
    ...requestConfig,
  });
  return res.data;
}

export function deleteV1LicensesIdPackagesPackageMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = deleteV1LicensesIdPackagesPackageMutationKey();
  return mutationOptions<
    DeleteV1LicensesIdPackagesPackageMutationResponse,
    ResponseErrorConfig<DeleteV1LicensesIdPackagesPackage404>,
    {
      id: DeleteV1LicensesIdPackagesPackagePathParams["id"];
      package: DeleteV1LicensesIdPackagesPackagePathParams["package"];
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, package }) => {
      return deleteV1LicensesIdPackagesPackage(id, package, config);
    },
  });
}

/**
 * {@link /v1/licenses/:id/packages/:package}
 */
export function useDeleteV1LicensesIdPackagesPackage<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteV1LicensesIdPackagesPackageMutationResponse,
      ResponseErrorConfig<DeleteV1LicensesIdPackagesPackage404>,
      {
        id: DeleteV1LicensesIdPackagesPackagePathParams["id"];
        package: DeleteV1LicensesIdPackagesPackagePathParams["package"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    deleteV1LicensesIdPackagesPackageMutationKey();

  const baseOptions = deleteV1LicensesIdPackagesPackageMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteV1LicensesIdPackagesPackageMutationResponse,
    ResponseErrorConfig<DeleteV1LicensesIdPackagesPackage404>,
    {
      id: DeleteV1LicensesIdPackagesPackagePathParams["id"];
      package: DeleteV1LicensesIdPackagesPackagePathParams["package"];
    },
    TContext
  >;

  return useMutation<
    DeleteV1LicensesIdPackagesPackageMutationResponse,
    ResponseErrorConfig<DeleteV1LicensesIdPackagesPackage404>,
    {
      id: DeleteV1LicensesIdPackagesPackagePathParams["id"];
      package: DeleteV1LicensesIdPackagesPackagePathParams["package"];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteV1LicensesIdPackagesPackageMutationResponse,
    ResponseErrorConfig<DeleteV1LicensesIdPackagesPackage404>,
    {
      id: DeleteV1LicensesIdPackagesPackagePathParams["id"];
      package: DeleteV1LicensesIdPackagesPackagePathParams["package"];
    },
    TContext
  >;
}
