/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  DeleteV1LicensesIdCapabilitiesCapabilityMutationResponse,
  DeleteV1LicensesIdCapabilitiesCapabilityPathParams,
  DeleteV1LicensesIdCapabilitiesCapability404,
} from "../gen/DeleteV1LicensesIdCapabilitiesCapability.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteV1LicensesIdCapabilitiesCapabilityMutationKey = () =>
  [{ url: "/v1/licenses/:id/capabilities/:capability" }] as const;

export type DeleteV1LicensesIdCapabilitiesCapabilityMutationKey = ReturnType<
  typeof deleteV1LicensesIdCapabilitiesCapabilityMutationKey
>;

/**
 * {@link /v1/licenses/:id/capabilities/:capability}
 */
export async function deleteV1LicensesIdCapabilitiesCapability(
  id: DeleteV1LicensesIdCapabilitiesCapabilityPathParams["id"],
  capability: DeleteV1LicensesIdCapabilitiesCapabilityPathParams["capability"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteV1LicensesIdCapabilitiesCapabilityMutationResponse,
    ResponseErrorConfig<DeleteV1LicensesIdCapabilitiesCapability404>,
    unknown
  >({
    method: "DELETE",
    url: `/v1/licenses/${id}/capabilities/${capability}`,
    ...requestConfig,
  });
  return res.data;
}

export function deleteV1LicensesIdCapabilitiesCapabilityMutationOptions<
  TContext = unknown,
>(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = deleteV1LicensesIdCapabilitiesCapabilityMutationKey();
  return mutationOptions<
    DeleteV1LicensesIdCapabilitiesCapabilityMutationResponse,
    ResponseErrorConfig<DeleteV1LicensesIdCapabilitiesCapability404>,
    {
      id: DeleteV1LicensesIdCapabilitiesCapabilityPathParams["id"];
      capability: DeleteV1LicensesIdCapabilitiesCapabilityPathParams["capability"];
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, capability }) => {
      return deleteV1LicensesIdCapabilitiesCapability(id, capability, config);
    },
  });
}

/**
 * {@link /v1/licenses/:id/capabilities/:capability}
 */
export function useDeleteV1LicensesIdCapabilitiesCapability<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteV1LicensesIdCapabilitiesCapabilityMutationResponse,
      ResponseErrorConfig<DeleteV1LicensesIdCapabilitiesCapability404>,
      {
        id: DeleteV1LicensesIdCapabilitiesCapabilityPathParams["id"];
        capability: DeleteV1LicensesIdCapabilitiesCapabilityPathParams["capability"];
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    deleteV1LicensesIdCapabilitiesCapabilityMutationKey();

  const baseOptions = deleteV1LicensesIdCapabilitiesCapabilityMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteV1LicensesIdCapabilitiesCapabilityMutationResponse,
    ResponseErrorConfig<DeleteV1LicensesIdCapabilitiesCapability404>,
    {
      id: DeleteV1LicensesIdCapabilitiesCapabilityPathParams["id"];
      capability: DeleteV1LicensesIdCapabilitiesCapabilityPathParams["capability"];
    },
    TContext
  >;

  return useMutation<
    DeleteV1LicensesIdCapabilitiesCapabilityMutationResponse,
    ResponseErrorConfig<DeleteV1LicensesIdCapabilitiesCapability404>,
    {
      id: DeleteV1LicensesIdCapabilitiesCapabilityPathParams["id"];
      capability: DeleteV1LicensesIdCapabilitiesCapabilityPathParams["capability"];
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteV1LicensesIdCapabilitiesCapabilityMutationResponse,
    ResponseErrorConfig<DeleteV1LicensesIdCapabilitiesCapability404>,
    {
      id: DeleteV1LicensesIdCapabilitiesCapabilityPathParams["id"];
      capability: DeleteV1LicensesIdCapabilitiesCapabilityPathParams["capability"];
    },
    TContext
  >;
}
