/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  DeleteV1ApiKeysIdMutationResponse,
  DeleteV1ApiKeysIdPathParams,
  DeleteV1ApiKeysId404,
} from "../gen/DeleteV1ApiKeysId.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteV1ApiKeysIdMutationKey = () =>
  [{ url: "/v1/api-keys/:id" }] as const;

export type DeleteV1ApiKeysIdMutationKey = ReturnType<
  typeof deleteV1ApiKeysIdMutationKey
>;

/**
 * {@link /v1/api-keys/:id}
 */
export async function deleteV1ApiKeysId(
  id: DeleteV1ApiKeysIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    DeleteV1ApiKeysIdMutationResponse,
    ResponseErrorConfig<DeleteV1ApiKeysId404>,
    unknown
  >({ method: "DELETE", url: `/v1/api-keys/${id}`, ...requestConfig });
  return res.data;
}

export function deleteV1ApiKeysIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = deleteV1ApiKeysIdMutationKey();
  return mutationOptions<
    DeleteV1ApiKeysIdMutationResponse,
    ResponseErrorConfig<DeleteV1ApiKeysId404>,
    { id: DeleteV1ApiKeysIdPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return deleteV1ApiKeysId(id, config);
    },
  });
}

/**
 * {@link /v1/api-keys/:id}
 */
export function useDeleteV1ApiKeysId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeleteV1ApiKeysIdMutationResponse,
      ResponseErrorConfig<DeleteV1ApiKeysId404>,
      { id: DeleteV1ApiKeysIdPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? deleteV1ApiKeysIdMutationKey();

  const baseOptions = deleteV1ApiKeysIdMutationOptions(
    config,
  ) as UseMutationOptions<
    DeleteV1ApiKeysIdMutationResponse,
    ResponseErrorConfig<DeleteV1ApiKeysId404>,
    { id: DeleteV1ApiKeysIdPathParams["id"] },
    TContext
  >;

  return useMutation<
    DeleteV1ApiKeysIdMutationResponse,
    ResponseErrorConfig<DeleteV1ApiKeysId404>,
    { id: DeleteV1ApiKeysIdPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    DeleteV1ApiKeysIdMutationResponse,
    ResponseErrorConfig<DeleteV1ApiKeysId404>,
    { id: DeleteV1ApiKeysIdPathParams["id"] },
    TContext
  >;
}
