/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  GetV1ApiKeysIdQueryResponse,
  GetV1ApiKeysIdPathParams,
  GetV1ApiKeysId404,
} from "../gen/GetV1ApiKeysId.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1ApiKeysIdQueryKey = (id: GetV1ApiKeysIdPathParams["id"]) =>
  [{ url: "/v1/api-keys/:id", params: { id: id } }] as const;

export type GetV1ApiKeysIdQueryKey = ReturnType<typeof getV1ApiKeysIdQueryKey>;

/**
 * {@link /v1/api-keys/:id}
 */
export async function getV1ApiKeysId(
  id: GetV1ApiKeysIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1ApiKeysIdQueryResponse,
    ResponseErrorConfig<GetV1ApiKeysId404>,
    unknown
  >({ method: "GET", url: `/v1/api-keys/${id}`, ...requestConfig });
  return res.data;
}

export function getV1ApiKeysIdQueryOptions(
  id: GetV1ApiKeysIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1ApiKeysIdQueryKey(id);
  return queryOptions<
    GetV1ApiKeysIdQueryResponse,
    ResponseErrorConfig<GetV1ApiKeysId404>,
    GetV1ApiKeysIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1ApiKeysId(id, config);
    },
  });
}

/**
 * {@link /v1/api-keys/:id}
 */
export function useGetV1ApiKeysId<
  TData = GetV1ApiKeysIdQueryResponse,
  TQueryData = GetV1ApiKeysIdQueryResponse,
  TQueryKey extends QueryKey = GetV1ApiKeysIdQueryKey,
>(
  id: GetV1ApiKeysIdPathParams["id"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1ApiKeysIdQueryResponse,
        ResponseErrorConfig<GetV1ApiKeysId404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getV1ApiKeysIdQueryKey(id);

  const query = useQuery(
    {
      ...getV1ApiKeysIdQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetV1ApiKeysId404>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
