/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type { GetVersionQueryResponse } from "../gen/GetVersion.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getVersionQueryKey = () => [{ url: "/version" }] as const;

export type GetVersionQueryKey = ReturnType<typeof getVersionQueryKey>;

/**
 * {@link /version}
 */
export async function getVersion(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetVersionQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/version`, ...requestConfig });
  return res.data;
}

export function getVersionQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getVersionQueryKey();
  return queryOptions<
    GetVersionQueryResponse,
    ResponseErrorConfig<Error>,
    GetVersionQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getVersion(config);
    },
  });
}

/**
 * {@link /version}
 */
export function useGetVersion<
  TData = GetVersionQueryResponse,
  TQueryData = GetVersionQueryResponse,
  TQueryKey extends QueryKey = GetVersionQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetVersionQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getVersionQueryKey();

  const query = useQuery(
    {
      ...getVersionQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
