/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  GetV1LicensesIdQueryResponse,
  GetV1LicensesIdPathParams,
  GetV1LicensesId404,
} from "../gen/GetV1LicensesId.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1LicensesIdQueryKey = (id: GetV1LicensesIdPathParams["id"]) =>
  [{ url: "/v1/licenses/:id", params: { id: id } }] as const;

export type GetV1LicensesIdQueryKey = ReturnType<
  typeof getV1LicensesIdQueryKey
>;

/**
 * {@link /v1/licenses/:id}
 */
export async function getV1LicensesId(
  id: GetV1LicensesIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1LicensesIdQueryResponse,
    ResponseErrorConfig<GetV1LicensesId404>,
    unknown
  >({ method: "GET", url: `/v1/licenses/${id}`, ...requestConfig });
  return res.data;
}

export function getV1LicensesIdQueryOptions(
  id: GetV1LicensesIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1LicensesIdQueryKey(id);
  return queryOptions<
    GetV1LicensesIdQueryResponse,
    ResponseErrorConfig<GetV1LicensesId404>,
    GetV1LicensesIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1LicensesId(id, config);
    },
  });
}

/**
 * {@link /v1/licenses/:id}
 */
export function useGetV1LicensesId<
  TData = GetV1LicensesIdQueryResponse,
  TQueryData = GetV1LicensesIdQueryResponse,
  TQueryKey extends QueryKey = GetV1LicensesIdQueryKey,
>(
  id: GetV1LicensesIdPathParams["id"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1LicensesIdQueryResponse,
        ResponseErrorConfig<GetV1LicensesId404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getV1LicensesIdQueryKey(id);

  const query = useQuery(
    {
      ...getV1LicensesIdQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetV1LicensesId404>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
