/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  GetV1LicensesQueryResponse,
  GetV1LicensesQueryParams,
} from "../gen/GetV1Licenses.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1LicensesSuspenseQueryKey = (
  params: GetV1LicensesQueryParams = {},
) => [{ url: "/v1/licenses" }, ...(params ? [params] : [])] as const;

export type GetV1LicensesSuspenseQueryKey = ReturnType<
  typeof getV1LicensesSuspenseQueryKey
>;

/**
 * {@link /v1/licenses}
 */
export async function getV1LicensesSuspense(
  params?: GetV1LicensesQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1LicensesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/v1/licenses`, params, ...requestConfig });
  return res.data;
}

export function getV1LicensesSuspenseQueryOptions(
  params?: GetV1LicensesQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1LicensesSuspenseQueryKey(params);
  return queryOptions<
    GetV1LicensesQueryResponse,
    ResponseErrorConfig<Error>,
    GetV1LicensesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1LicensesSuspense(params, config);
    },
  });
}

/**
 * {@link /v1/licenses}
 */
export function useGetV1LicensesSuspense<
  TData = GetV1LicensesQueryResponse,
  TQueryKey extends QueryKey = GetV1LicensesSuspenseQueryKey,
>(
  params?: GetV1LicensesQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetV1LicensesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getV1LicensesSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getV1LicensesSuspenseQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
