/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  GetV1DevelopersIdQueryResponse,
  GetV1DevelopersIdPathParams,
  GetV1DevelopersId404,
} from "../gen/GetV1DevelopersId.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1DevelopersIdSuspenseQueryKey = (
  id: GetV1DevelopersIdPathParams["id"],
) => [{ url: "/v1/developers/:id", params: { id: id } }] as const;

export type GetV1DevelopersIdSuspenseQueryKey = ReturnType<
  typeof getV1DevelopersIdSuspenseQueryKey
>;

/**
 * {@link /v1/developers/:id}
 */
export async function getV1DevelopersIdSuspense(
  id: GetV1DevelopersIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1DevelopersIdQueryResponse,
    ResponseErrorConfig<GetV1DevelopersId404>,
    unknown
  >({ method: "GET", url: `/v1/developers/${id}`, ...requestConfig });
  return res.data;
}

export function getV1DevelopersIdSuspenseQueryOptions(
  id: GetV1DevelopersIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1DevelopersIdSuspenseQueryKey(id);
  return queryOptions<
    GetV1DevelopersIdQueryResponse,
    ResponseErrorConfig<GetV1DevelopersId404>,
    GetV1DevelopersIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1DevelopersIdSuspense(id, config);
    },
  });
}

/**
 * {@link /v1/developers/:id}
 */
export function useGetV1DevelopersIdSuspense<
  TData = GetV1DevelopersIdQueryResponse,
  TQueryKey extends QueryKey = GetV1DevelopersIdSuspenseQueryKey,
>(
  id: GetV1DevelopersIdPathParams["id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetV1DevelopersIdQueryResponse,
        ResponseErrorConfig<GetV1DevelopersId404>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getV1DevelopersIdSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...getV1DevelopersIdSuspenseQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetV1DevelopersId404>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
