/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type { GetV1LatestVersionQueryResponse } from "../gen/GetV1LatestVersion.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1LatestVersionQueryKey = () =>
  [{ url: "/v1/latest-version" }] as const;

export type GetV1LatestVersionQueryKey = ReturnType<
  typeof getV1LatestVersionQueryKey
>;

/**
 * {@link /v1/latest-version}
 */
export async function getV1LatestVersion(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1LatestVersionQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/v1/latest-version`, ...requestConfig });
  return res.data;
}

export function getV1LatestVersionQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1LatestVersionQueryKey();
  return queryOptions<
    GetV1LatestVersionQueryResponse,
    ResponseErrorConfig<Error>,
    GetV1LatestVersionQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1LatestVersion(config);
    },
  });
}

/**
 * {@link /v1/latest-version}
 */
export function useGetV1LatestVersion<
  TData = GetV1LatestVersionQueryResponse,
  TQueryData = GetV1LatestVersionQueryResponse,
  TQueryKey extends QueryKey = GetV1LatestVersionQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1LatestVersionQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getV1LatestVersionQueryKey();

  const query = useQuery(
    {
      ...getV1LatestVersionQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
