/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  GetV1DevelopersIdQueryResponse,
  GetV1DevelopersIdPathParams,
  GetV1DevelopersId404,
} from "../gen/GetV1DevelopersId.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1DevelopersIdQueryKey = (
  id: GetV1DevelopersIdPathParams["id"],
) => [{ url: "/v1/developers/:id", params: { id: id } }] as const;

export type GetV1DevelopersIdQueryKey = ReturnType<
  typeof getV1DevelopersIdQueryKey
>;

/**
 * {@link /v1/developers/:id}
 */
export async function getV1DevelopersId(
  id: GetV1DevelopersIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1DevelopersIdQueryResponse,
    ResponseErrorConfig<GetV1DevelopersId404>,
    unknown
  >({ method: "GET", url: `/v1/developers/${id}`, ...requestConfig });
  return res.data;
}

export function getV1DevelopersIdQueryOptions(
  id: GetV1DevelopersIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1DevelopersIdQueryKey(id);
  return queryOptions<
    GetV1DevelopersIdQueryResponse,
    ResponseErrorConfig<GetV1DevelopersId404>,
    GetV1DevelopersIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1DevelopersId(id, config);
    },
  });
}

/**
 * {@link /v1/developers/:id}
 */
export function useGetV1DevelopersId<
  TData = GetV1DevelopersIdQueryResponse,
  TQueryData = GetV1DevelopersIdQueryResponse,
  TQueryKey extends QueryKey = GetV1DevelopersIdQueryKey,
>(
  id: GetV1DevelopersIdPathParams["id"],
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1DevelopersIdQueryResponse,
        ResponseErrorConfig<GetV1DevelopersId404>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getV1DevelopersIdQueryKey(id);

  const query = useQuery(
    {
      ...getV1DevelopersIdQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetV1DevelopersId404>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
