/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type { GetVersionQueryResponse } from "../gen/GetVersion.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getVersionSuspenseQueryKey = () => [{ url: "/version" }] as const;

export type GetVersionSuspenseQueryKey = ReturnType<
  typeof getVersionSuspenseQueryKey
>;

/**
 * {@link /version}
 */
export async function getVersionSuspense(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetVersionQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/version`, ...requestConfig });
  return res.data;
}

export function getVersionSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getVersionSuspenseQueryKey();
  return queryOptions<
    GetVersionQueryResponse,
    ResponseErrorConfig<Error>,
    GetVersionQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getVersionSuspense(config);
    },
  });
}

/**
 * {@link /version}
 */
export function useGetVersionSuspense<
  TData = GetVersionQueryResponse,
  TQueryKey extends QueryKey = GetVersionSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetVersionQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getVersionSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getVersionSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
