/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  GetV1ApiKeysQueryResponse,
  GetV1ApiKeysQueryParams,
} from "../gen/GetV1ApiKeys.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1ApiKeysSuspenseQueryKey = (
  params: GetV1ApiKeysQueryParams = {},
) => [{ url: "/v1/api-keys" }, ...(params ? [params] : [])] as const;

export type GetV1ApiKeysSuspenseQueryKey = ReturnType<
  typeof getV1ApiKeysSuspenseQueryKey
>;

/**
 * {@link /v1/api-keys}
 */
export async function getV1ApiKeysSuspense(
  params?: GetV1ApiKeysQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1ApiKeysQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/v1/api-keys`, params, ...requestConfig });
  return res.data;
}

export function getV1ApiKeysSuspenseQueryOptions(
  params?: GetV1ApiKeysQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1ApiKeysSuspenseQueryKey(params);
  return queryOptions<
    GetV1ApiKeysQueryResponse,
    ResponseErrorConfig<Error>,
    GetV1ApiKeysQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1ApiKeysSuspense(params, config);
    },
  });
}

/**
 * {@link /v1/api-keys}
 */
export function useGetV1ApiKeysSuspense<
  TData = GetV1ApiKeysQueryResponse,
  TQueryKey extends QueryKey = GetV1ApiKeysSuspenseQueryKey,
>(
  params?: GetV1ApiKeysQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetV1ApiKeysQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getV1ApiKeysSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getV1ApiKeysSuspenseQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
