/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type { GetV1OrganizationsQueryResponse } from "../gen/GetV1Organizations.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1OrganizationsSuspenseQueryKey = () =>
  [{ url: "/v1/organizations" }] as const;

export type GetV1OrganizationsSuspenseQueryKey = ReturnType<
  typeof getV1OrganizationsSuspenseQueryKey
>;

/**
 * {@link /v1/organizations}
 */
export async function getV1OrganizationsSuspense(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1OrganizationsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/v1/organizations`, ...requestConfig });
  return res.data;
}

export function getV1OrganizationsSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1OrganizationsSuspenseQueryKey();
  return queryOptions<
    GetV1OrganizationsQueryResponse,
    ResponseErrorConfig<Error>,
    GetV1OrganizationsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1OrganizationsSuspense(config);
    },
  });
}

/**
 * {@link /v1/organizations}
 */
export function useGetV1OrganizationsSuspense<
  TData = GetV1OrganizationsQueryResponse,
  TQueryKey extends QueryKey = GetV1OrganizationsSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetV1OrganizationsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getV1OrganizationsSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getV1OrganizationsSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
