/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type { GetV1LatestVersionQueryResponse } from "../gen/GetV1LatestVersion.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1LatestVersionSuspenseQueryKey = () =>
  [{ url: "/v1/latest-version" }] as const;

export type GetV1LatestVersionSuspenseQueryKey = ReturnType<
  typeof getV1LatestVersionSuspenseQueryKey
>;

/**
 * {@link /v1/latest-version}
 */
export async function getV1LatestVersionSuspense(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1LatestVersionQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/v1/latest-version`, ...requestConfig });
  return res.data;
}

export function getV1LatestVersionSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1LatestVersionSuspenseQueryKey();
  return queryOptions<
    GetV1LatestVersionQueryResponse,
    ResponseErrorConfig<Error>,
    GetV1LatestVersionQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1LatestVersionSuspense(config);
    },
  });
}

/**
 * {@link /v1/latest-version}
 */
export function useGetV1LatestVersionSuspense<
  TData = GetV1LatestVersionQueryResponse,
  TQueryKey extends QueryKey = GetV1LatestVersionSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetV1LatestVersionQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getV1LatestVersionSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getV1LatestVersionSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
