/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  GetV1ApiKeysQueryResponse,
  GetV1ApiKeysQueryParams,
} from "../gen/GetV1ApiKeys.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1ApiKeysQueryKey = (params: GetV1ApiKeysQueryParams = {}) =>
  [{ url: "/v1/api-keys" }, ...(params ? [params] : [])] as const;

export type GetV1ApiKeysQueryKey = ReturnType<typeof getV1ApiKeysQueryKey>;

/**
 * {@link /v1/api-keys}
 */
export async function getV1ApiKeys(
  params?: GetV1ApiKeysQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1ApiKeysQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/v1/api-keys`, params, ...requestConfig });
  return res.data;
}

export function getV1ApiKeysQueryOptions(
  params?: GetV1ApiKeysQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1ApiKeysQueryKey(params);
  return queryOptions<
    GetV1ApiKeysQueryResponse,
    ResponseErrorConfig<Error>,
    GetV1ApiKeysQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1ApiKeys(params, config);
    },
  });
}

/**
 * {@link /v1/api-keys}
 */
export function useGetV1ApiKeys<
  TData = GetV1ApiKeysQueryResponse,
  TQueryData = GetV1ApiKeysQueryResponse,
  TQueryKey extends QueryKey = GetV1ApiKeysQueryKey,
>(
  params?: GetV1ApiKeysQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1ApiKeysQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getV1ApiKeysQueryKey(params);

  const query = useQuery(
    {
      ...getV1ApiKeysQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
