/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  GetV1LicensesQueryResponse,
  GetV1LicensesQueryParams,
} from "../gen/GetV1Licenses.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1LicensesQueryKey = (params: GetV1LicensesQueryParams = {}) =>
  [{ url: "/v1/licenses" }, ...(params ? [params] : [])] as const;

export type GetV1LicensesQueryKey = ReturnType<typeof getV1LicensesQueryKey>;

/**
 * {@link /v1/licenses}
 */
export async function getV1Licenses(
  params?: GetV1LicensesQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1LicensesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/v1/licenses`, params, ...requestConfig });
  return res.data;
}

export function getV1LicensesQueryOptions(
  params?: GetV1LicensesQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1LicensesQueryKey(params);
  return queryOptions<
    GetV1LicensesQueryResponse,
    ResponseErrorConfig<Error>,
    GetV1LicensesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1Licenses(params, config);
    },
  });
}

/**
 * {@link /v1/licenses}
 */
export function useGetV1Licenses<
  TData = GetV1LicensesQueryResponse,
  TQueryData = GetV1LicensesQueryResponse,
  TQueryKey extends QueryKey = GetV1LicensesQueryKey,
>(
  params?: GetV1LicensesQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1LicensesQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getV1LicensesQueryKey(params);

  const query = useQuery(
    {
      ...getV1LicensesQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
