/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  GetV1LicensesIdQueryResponse,
  GetV1LicensesIdPathParams,
  GetV1LicensesId404,
} from "../gen/GetV1LicensesId.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1LicensesIdSuspenseQueryKey = (
  id: GetV1LicensesIdPathParams["id"],
) => [{ url: "/v1/licenses/:id", params: { id: id } }] as const;

export type GetV1LicensesIdSuspenseQueryKey = ReturnType<
  typeof getV1LicensesIdSuspenseQueryKey
>;

/**
 * {@link /v1/licenses/:id}
 */
export async function getV1LicensesIdSuspense(
  id: GetV1LicensesIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1LicensesIdQueryResponse,
    ResponseErrorConfig<GetV1LicensesId404>,
    unknown
  >({ method: "GET", url: `/v1/licenses/${id}`, ...requestConfig });
  return res.data;
}

export function getV1LicensesIdSuspenseQueryOptions(
  id: GetV1LicensesIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1LicensesIdSuspenseQueryKey(id);
  return queryOptions<
    GetV1LicensesIdQueryResponse,
    ResponseErrorConfig<GetV1LicensesId404>,
    GetV1LicensesIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1LicensesIdSuspense(id, config);
    },
  });
}

/**
 * {@link /v1/licenses/:id}
 */
export function useGetV1LicensesIdSuspense<
  TData = GetV1LicensesIdQueryResponse,
  TQueryKey extends QueryKey = GetV1LicensesIdSuspenseQueryKey,
>(
  id: GetV1LicensesIdPathParams["id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetV1LicensesIdQueryResponse,
        ResponseErrorConfig<GetV1LicensesId404>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getV1LicensesIdSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...getV1LicensesIdSuspenseQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<GetV1LicensesId404>
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
