/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  GetV1DevelopersQueryResponse,
  GetV1DevelopersQueryParams,
} from "../gen/GetV1Developers.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1DevelopersSuspenseQueryKey = (
  params: GetV1DevelopersQueryParams = {},
) => [{ url: "/v1/developers" }, ...(params ? [params] : [])] as const;

export type GetV1DevelopersSuspenseQueryKey = ReturnType<
  typeof getV1DevelopersSuspenseQueryKey
>;

/**
 * {@link /v1/developers}
 */
export async function getV1DevelopersSuspense(
  params?: GetV1DevelopersQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1DevelopersQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/v1/developers`, params, ...requestConfig });
  return res.data;
}

export function getV1DevelopersSuspenseQueryOptions(
  params?: GetV1DevelopersQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1DevelopersSuspenseQueryKey(params);
  return queryOptions<
    GetV1DevelopersQueryResponse,
    ResponseErrorConfig<Error>,
    GetV1DevelopersQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1DevelopersSuspense(params, config);
    },
  });
}

/**
 * {@link /v1/developers}
 */
export function useGetV1DevelopersSuspense<
  TData = GetV1DevelopersQueryResponse,
  TQueryKey extends QueryKey = GetV1DevelopersSuspenseQueryKey,
>(
  params?: GetV1DevelopersQueryParams,
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetV1DevelopersQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getV1DevelopersSuspenseQueryKey(params);

  const query = useSuspenseQuery(
    {
      ...getV1DevelopersSuspenseQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
