/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  GetV1OrganizationsIdQueryResponse,
  GetV1OrganizationsIdPathParams,
  GetV1OrganizationsId404,
} from "../gen/GetV1OrganizationsId.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
} from "@tanstack/react-query";
import {
  infiniteQueryOptions,
  useSuspenseInfiniteQuery,
} from "@tanstack/react-query";

export const getV1OrganizationsIdSuspenseInfiniteQueryKey = (
  id: GetV1OrganizationsIdPathParams["id"],
) => [{ url: "/v1/organizations/:id", params: { id: id } }] as const;

export type GetV1OrganizationsIdSuspenseInfiniteQueryKey = ReturnType<
  typeof getV1OrganizationsIdSuspenseInfiniteQueryKey
>;

/**
 * {@link /v1/organizations/:id}
 */
export async function getV1OrganizationsIdSuspenseInfinite(
  id: GetV1OrganizationsIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1OrganizationsIdQueryResponse,
    ResponseErrorConfig<GetV1OrganizationsId404>,
    unknown
  >({ method: "GET", url: `/v1/organizations/${id}`, ...requestConfig });
  return res.data;
}

export function getV1OrganizationsIdSuspenseInfiniteQueryOptions(
  id: GetV1OrganizationsIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1OrganizationsIdSuspenseInfiniteQueryKey(id);
  return infiniteQueryOptions<
    GetV1OrganizationsIdQueryResponse,
    ResponseErrorConfig<GetV1OrganizationsId404>,
    InfiniteData<GetV1OrganizationsIdQueryResponse>,
    typeof queryKey,
    number
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1OrganizationsIdSuspenseInfinite(id, config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage, _allPages, lastPageParam) =>
      Array.isArray(lastPage) && lastPage.length === 0
        ? undefined
        : lastPageParam + 1,
    getPreviousPageParam: (_firstPage, _allPages, firstPageParam) =>
      firstPageParam <= 1 ? undefined : firstPageParam - 1,
  });
}

/**
 * {@link /v1/organizations/:id}
 */
export function useGetV1OrganizationsIdSuspenseInfinite<
  TQueryFnData = GetV1OrganizationsIdQueryResponse,
  TError = ResponseErrorConfig<GetV1OrganizationsId404>,
  TData = InfiniteData<TQueryFnData>,
  TQueryKey extends QueryKey = GetV1OrganizationsIdSuspenseInfiniteQueryKey,
  TPageParam = number,
>(
  id: GetV1OrganizationsIdPathParams["id"],
  options: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        TQueryFnData,
        TError,
        TData,
        TQueryKey,
        TPageParam
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getV1OrganizationsIdSuspenseInfiniteQueryKey(id);

  const query = useSuspenseInfiniteQuery(
    {
      ...getV1OrganizationsIdSuspenseInfiniteQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseInfiniteQueryOptions<
      TQueryFnData,
      TError,
      TData,
      TQueryKey,
      TPageParam
    >,
    queryClient,
  ) as UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
