/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  GetV1ApiKeysIdQueryResponse,
  GetV1ApiKeysIdPathParams,
  GetV1ApiKeysId404,
} from "../gen/GetV1ApiKeysId.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
} from "@tanstack/react-query";
import {
  infiniteQueryOptions,
  useSuspenseInfiniteQuery,
} from "@tanstack/react-query";

export const getV1ApiKeysIdSuspenseInfiniteQueryKey = (
  id: GetV1ApiKeysIdPathParams["id"],
) => [{ url: "/v1/api-keys/:id", params: { id: id } }] as const;

export type GetV1ApiKeysIdSuspenseInfiniteQueryKey = ReturnType<
  typeof getV1ApiKeysIdSuspenseInfiniteQueryKey
>;

/**
 * {@link /v1/api-keys/:id}
 */
export async function getV1ApiKeysIdSuspenseInfinite(
  id: GetV1ApiKeysIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1ApiKeysIdQueryResponse,
    ResponseErrorConfig<GetV1ApiKeysId404>,
    unknown
  >({ method: "GET", url: `/v1/api-keys/${id}`, ...requestConfig });
  return res.data;
}

export function getV1ApiKeysIdSuspenseInfiniteQueryOptions(
  id: GetV1ApiKeysIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1ApiKeysIdSuspenseInfiniteQueryKey(id);
  return infiniteQueryOptions<
    GetV1ApiKeysIdQueryResponse,
    ResponseErrorConfig<GetV1ApiKeysId404>,
    InfiniteData<GetV1ApiKeysIdQueryResponse>,
    typeof queryKey,
    number
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1ApiKeysIdSuspenseInfinite(id, config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage, _allPages, lastPageParam) =>
      Array.isArray(lastPage) && lastPage.length === 0
        ? undefined
        : lastPageParam + 1,
    getPreviousPageParam: (_firstPage, _allPages, firstPageParam) =>
      firstPageParam <= 1 ? undefined : firstPageParam - 1,
  });
}

/**
 * {@link /v1/api-keys/:id}
 */
export function useGetV1ApiKeysIdSuspenseInfinite<
  TQueryFnData = GetV1ApiKeysIdQueryResponse,
  TError = ResponseErrorConfig<GetV1ApiKeysId404>,
  TData = InfiniteData<TQueryFnData>,
  TQueryKey extends QueryKey = GetV1ApiKeysIdSuspenseInfiniteQueryKey,
  TPageParam = number,
>(
  id: GetV1ApiKeysIdPathParams["id"],
  options: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        TQueryFnData,
        TError,
        TData,
        TQueryKey,
        TPageParam
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getV1ApiKeysIdSuspenseInfiniteQueryKey(id);

  const query = useSuspenseInfiniteQuery(
    {
      ...getV1ApiKeysIdSuspenseInfiniteQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseInfiniteQueryOptions<
      TQueryFnData,
      TError,
      TData,
      TQueryKey,
      TPageParam
    >,
    queryClient,
  ) as UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
