/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type { GetV1HealthQueryResponse } from "../gen/GetV1Health.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
} from "@tanstack/react-query";
import {
  infiniteQueryOptions,
  useSuspenseInfiniteQuery,
} from "@tanstack/react-query";

export const getV1HealthSuspenseInfiniteQueryKey = () =>
  [{ url: "/v1/health" }] as const;

export type GetV1HealthSuspenseInfiniteQueryKey = ReturnType<
  typeof getV1HealthSuspenseInfiniteQueryKey
>;

/**
 * {@link /v1/health}
 */
export async function getV1HealthSuspenseInfinite(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1HealthQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/v1/health`, ...requestConfig });
  return res.data;
}

export function getV1HealthSuspenseInfiniteQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1HealthSuspenseInfiniteQueryKey();
  return infiniteQueryOptions<
    GetV1HealthQueryResponse,
    ResponseErrorConfig<Error>,
    InfiniteData<GetV1HealthQueryResponse>,
    typeof queryKey,
    number
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1HealthSuspenseInfinite(config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage, _allPages, lastPageParam) =>
      Array.isArray(lastPage) && lastPage.length === 0
        ? undefined
        : lastPageParam + 1,
    getPreviousPageParam: (_firstPage, _allPages, firstPageParam) =>
      firstPageParam <= 1 ? undefined : firstPageParam - 1,
  });
}

/**
 * {@link /v1/health}
 */
export function useGetV1HealthSuspenseInfinite<
  TQueryFnData = GetV1HealthQueryResponse,
  TError = ResponseErrorConfig<Error>,
  TData = InfiniteData<TQueryFnData>,
  TQueryKey extends QueryKey = GetV1HealthSuspenseInfiniteQueryKey,
  TPageParam = number,
>(
  options: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        TQueryFnData,
        TError,
        TData,
        TQueryKey,
        TPageParam
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getV1HealthSuspenseInfiniteQueryKey();

  const query = useSuspenseInfiniteQuery(
    {
      ...getV1HealthSuspenseInfiniteQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseInfiniteQueryOptions<
      TQueryFnData,
      TError,
      TData,
      TQueryKey,
      TPageParam
    >,
    queryClient,
  ) as UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
