/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type { GetV1OrganizationsQueryResponse } from "../gen/GetV1Organizations.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1OrganizationsQueryKey = () =>
  [{ url: "/v1/organizations" }] as const;

export type GetV1OrganizationsQueryKey = ReturnType<
  typeof getV1OrganizationsQueryKey
>;

/**
 * {@link /v1/organizations}
 */
export async function getV1Organizations(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1OrganizationsQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/v1/organizations`, ...requestConfig });
  return res.data;
}

export function getV1OrganizationsQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1OrganizationsQueryKey();
  return queryOptions<
    GetV1OrganizationsQueryResponse,
    ResponseErrorConfig<Error>,
    GetV1OrganizationsQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1Organizations(config);
    },
  });
}

/**
 * {@link /v1/organizations}
 */
export function useGetV1Organizations<
  TData = GetV1OrganizationsQueryResponse,
  TQueryData = GetV1OrganizationsQueryResponse,
  TQueryKey extends QueryKey = GetV1OrganizationsQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1OrganizationsQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getV1OrganizationsQueryKey();

  const query = useQuery(
    {
      ...getV1OrganizationsQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
