/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type { GetV1HealthQueryResponse } from "../gen/GetV1Health.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1HealthSuspenseQueryKey = () =>
  [{ url: "/v1/health" }] as const;

export type GetV1HealthSuspenseQueryKey = ReturnType<
  typeof getV1HealthSuspenseQueryKey
>;

/**
 * {@link /v1/health}
 */
export async function getV1HealthSuspense(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1HealthQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/v1/health`, ...requestConfig });
  return res.data;
}

export function getV1HealthSuspenseQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1HealthSuspenseQueryKey();
  return queryOptions<
    GetV1HealthQueryResponse,
    ResponseErrorConfig<Error>,
    GetV1HealthQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1HealthSuspense(config);
    },
  });
}

/**
 * {@link /v1/health}
 */
export function useGetV1HealthSuspense<
  TData = GetV1HealthQueryResponse,
  TQueryKey extends QueryKey = GetV1HealthSuspenseQueryKey,
>(
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetV1HealthQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getV1HealthSuspenseQueryKey();

  const query = useSuspenseQuery(
    {
      ...getV1HealthSuspenseQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
