/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  GetV1DevelopersIdQueryResponse,
  GetV1DevelopersIdPathParams,
  GetV1DevelopersId404,
} from "../gen/GetV1DevelopersId.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
} from "@tanstack/react-query";
import {
  infiniteQueryOptions,
  useSuspenseInfiniteQuery,
} from "@tanstack/react-query";

export const getV1DevelopersIdSuspenseInfiniteQueryKey = (
  id: GetV1DevelopersIdPathParams["id"],
) => [{ url: "/v1/developers/:id", params: { id: id } }] as const;

export type GetV1DevelopersIdSuspenseInfiniteQueryKey = ReturnType<
  typeof getV1DevelopersIdSuspenseInfiniteQueryKey
>;

/**
 * {@link /v1/developers/:id}
 */
export async function getV1DevelopersIdSuspenseInfinite(
  id: GetV1DevelopersIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1DevelopersIdQueryResponse,
    ResponseErrorConfig<GetV1DevelopersId404>,
    unknown
  >({ method: "GET", url: `/v1/developers/${id}`, ...requestConfig });
  return res.data;
}

export function getV1DevelopersIdSuspenseInfiniteQueryOptions(
  id: GetV1DevelopersIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1DevelopersIdSuspenseInfiniteQueryKey(id);
  return infiniteQueryOptions<
    GetV1DevelopersIdQueryResponse,
    ResponseErrorConfig<GetV1DevelopersId404>,
    InfiniteData<GetV1DevelopersIdQueryResponse>,
    typeof queryKey,
    number
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1DevelopersIdSuspenseInfinite(id, config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage, _allPages, lastPageParam) =>
      Array.isArray(lastPage) && lastPage.length === 0
        ? undefined
        : lastPageParam + 1,
    getPreviousPageParam: (_firstPage, _allPages, firstPageParam) =>
      firstPageParam <= 1 ? undefined : firstPageParam - 1,
  });
}

/**
 * {@link /v1/developers/:id}
 */
export function useGetV1DevelopersIdSuspenseInfinite<
  TQueryFnData = GetV1DevelopersIdQueryResponse,
  TError = ResponseErrorConfig<GetV1DevelopersId404>,
  TData = InfiniteData<TQueryFnData>,
  TQueryKey extends QueryKey = GetV1DevelopersIdSuspenseInfiniteQueryKey,
  TPageParam = number,
>(
  id: GetV1DevelopersIdPathParams["id"],
  options: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        TQueryFnData,
        TError,
        TData,
        TQueryKey,
        TPageParam
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getV1DevelopersIdSuspenseInfiniteQueryKey(id);

  const query = useSuspenseInfiniteQuery(
    {
      ...getV1DevelopersIdSuspenseInfiniteQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseInfiniteQueryOptions<
      TQueryFnData,
      TError,
      TData,
      TQueryKey,
      TPageParam
    >,
    queryClient,
  ) as UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
