/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  GetV1ApiKeysIdQueryResponse,
  GetV1ApiKeysIdPathParams,
  GetV1ApiKeysId404,
} from "../gen/GetV1ApiKeysId.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getV1ApiKeysIdSuspenseQueryKey = (
  id: GetV1ApiKeysIdPathParams["id"],
) => [{ url: "/v1/api-keys/:id", params: { id: id } }] as const;

export type GetV1ApiKeysIdSuspenseQueryKey = ReturnType<
  typeof getV1ApiKeysIdSuspenseQueryKey
>;

/**
 * {@link /v1/api-keys/:id}
 */
export async function getV1ApiKeysIdSuspense(
  id: GetV1ApiKeysIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1ApiKeysIdQueryResponse,
    ResponseErrorConfig<GetV1ApiKeysId404>,
    unknown
  >({ method: "GET", url: `/v1/api-keys/${id}`, ...requestConfig });
  return res.data;
}

export function getV1ApiKeysIdSuspenseQueryOptions(
  id: GetV1ApiKeysIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1ApiKeysIdSuspenseQueryKey(id);
  return queryOptions<
    GetV1ApiKeysIdQueryResponse,
    ResponseErrorConfig<GetV1ApiKeysId404>,
    GetV1ApiKeysIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1ApiKeysIdSuspense(id, config);
    },
  });
}

/**
 * {@link /v1/api-keys/:id}
 */
export function useGetV1ApiKeysIdSuspense<
  TData = GetV1ApiKeysIdQueryResponse,
  TQueryKey extends QueryKey = GetV1ApiKeysIdSuspenseQueryKey,
>(
  id: GetV1ApiKeysIdPathParams["id"],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetV1ApiKeysIdQueryResponse,
        ResponseErrorConfig<GetV1ApiKeysId404>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getV1ApiKeysIdSuspenseQueryKey(id);

  const query = useSuspenseQuery(
    {
      ...getV1ApiKeysIdSuspenseQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseQueryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetV1ApiKeysId404>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
