/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type { GetV1HealthQueryResponse } from "../gen/GetV1Health.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getV1HealthQueryKey = () => [{ url: "/v1/health" }] as const;

export type GetV1HealthQueryKey = ReturnType<typeof getV1HealthQueryKey>;

/**
 * {@link /v1/health}
 */
export async function getV1Health(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1HealthQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/v1/health`, ...requestConfig });
  return res.data;
}

export function getV1HealthQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1HealthQueryKey();
  return queryOptions<
    GetV1HealthQueryResponse,
    ResponseErrorConfig<Error>,
    GetV1HealthQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1Health(config);
    },
  });
}

/**
 * {@link /v1/health}
 */
export function useGetV1Health<
  TData = GetV1HealthQueryResponse,
  TQueryData = GetV1HealthQueryResponse,
  TQueryKey extends QueryKey = GetV1HealthQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetV1HealthQueryResponse,
        ResponseErrorConfig<Error>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey = queryOptions?.queryKey ?? getV1HealthQueryKey();

  const query = useQuery(
    {
      ...getV1HealthQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & {
    queryKey: TQueryKey;
  };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
