/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  GetV1LicensesQueryResponse,
  GetV1LicensesQueryParams,
} from "../gen/GetV1Licenses.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
} from "@tanstack/react-query";
import {
  infiniteQueryOptions,
  useSuspenseInfiniteQuery,
} from "@tanstack/react-query";

export const getV1LicensesSuspenseInfiniteQueryKey = (
  params: GetV1LicensesQueryParams = {},
) => [{ url: "/v1/licenses" }, ...(params ? [params] : [])] as const;

export type GetV1LicensesSuspenseInfiniteQueryKey = ReturnType<
  typeof getV1LicensesSuspenseInfiniteQueryKey
>;

/**
 * {@link /v1/licenses}
 */
export async function getV1LicensesSuspenseInfinite(
  params?: GetV1LicensesQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1LicensesQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/v1/licenses`, params, ...requestConfig });
  return res.data;
}

export function getV1LicensesSuspenseInfiniteQueryOptions(
  params?: GetV1LicensesQueryParams,
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1LicensesSuspenseInfiniteQueryKey(params);
  return infiniteQueryOptions<
    GetV1LicensesQueryResponse,
    ResponseErrorConfig<Error>,
    InfiniteData<GetV1LicensesQueryResponse>,
    typeof queryKey,
    NonNullable<GetV1LicensesQueryParams["id"]>
  >({
    queryKey,
    queryFn: async ({ signal, pageParam }) => {
      config.signal = signal;

      params = {
        ...(params ?? {}),
        ["id"]: pageParam as unknown as GetV1LicensesQueryParams["id"],
      } as GetV1LicensesQueryParams;
      return getV1LicensesSuspenseInfinite(params, config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage, _allPages, lastPageParam) =>
      Array.isArray(lastPage) && lastPage.length === 0
        ? undefined
        : lastPageParam + 1,
    getPreviousPageParam: (_firstPage, _allPages, firstPageParam) =>
      firstPageParam <= 1 ? undefined : firstPageParam - 1,
  });
}

/**
 * {@link /v1/licenses}
 */
export function useGetV1LicensesSuspenseInfinite<
  TQueryFnData = GetV1LicensesQueryResponse,
  TError = ResponseErrorConfig<Error>,
  TData = InfiniteData<TQueryFnData>,
  TQueryKey extends QueryKey = GetV1LicensesSuspenseInfiniteQueryKey,
  TPageParam = NonNullable<GetV1LicensesQueryParams["id"]>,
>(
  params?: GetV1LicensesQueryParams,
  options: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        TQueryFnData,
        TError,
        TData,
        TQueryKey,
        TPageParam
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getV1LicensesSuspenseInfiniteQueryKey(params);

  const query = useSuspenseInfiniteQuery(
    {
      ...getV1LicensesSuspenseInfiniteQueryOptions(params, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseInfiniteQueryOptions<
      TQueryFnData,
      TError,
      TData,
      TQueryKey,
      TPageParam
    >,
    queryClient,
  ) as UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
