/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type { GetHealthQueryResponse } from "../gen/GetHealth.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
} from "@tanstack/react-query";
import {
  infiniteQueryOptions,
  useSuspenseInfiniteQuery,
} from "@tanstack/react-query";

export const getHealthSuspenseInfiniteQueryKey = () =>
  [{ url: "/health" }] as const;

export type GetHealthSuspenseInfiniteQueryKey = ReturnType<
  typeof getHealthSuspenseInfiniteQueryKey
>;

/**
 * {@link /health}
 */
export async function getHealthSuspenseInfinite(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetHealthQueryResponse,
    ResponseErrorConfig<Error>,
    unknown
  >({ method: "GET", url: `/health`, ...requestConfig });
  return res.data;
}

export function getHealthSuspenseInfiniteQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getHealthSuspenseInfiniteQueryKey();
  return infiniteQueryOptions<
    GetHealthQueryResponse,
    ResponseErrorConfig<Error>,
    InfiniteData<GetHealthQueryResponse>,
    typeof queryKey,
    number
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getHealthSuspenseInfinite(config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage, _allPages, lastPageParam) =>
      Array.isArray(lastPage) && lastPage.length === 0
        ? undefined
        : lastPageParam + 1,
    getPreviousPageParam: (_firstPage, _allPages, firstPageParam) =>
      firstPageParam <= 1 ? undefined : firstPageParam - 1,
  });
}

/**
 * {@link /health}
 */
export function useGetHealthSuspenseInfinite<
  TQueryFnData = GetHealthQueryResponse,
  TError = ResponseErrorConfig<Error>,
  TData = InfiniteData<TQueryFnData>,
  TQueryKey extends QueryKey = GetHealthSuspenseInfiniteQueryKey,
  TPageParam = number,
>(
  options: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        TQueryFnData,
        TError,
        TData,
        TQueryKey,
        TPageParam
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getHealthSuspenseInfiniteQueryKey();

  const query = useSuspenseInfiniteQuery(
    {
      ...getHealthSuspenseInfiniteQueryOptions(config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseInfiniteQueryOptions<
      TQueryFnData,
      TError,
      TData,
      TQueryKey,
      TPageParam
    >,
    queryClient,
  ) as UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
