/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  GetV1LicensesIdQueryResponse,
  GetV1LicensesIdPathParams,
  GetV1LicensesId404,
} from "../gen/GetV1LicensesId.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  InfiniteData,
  QueryKey,
  QueryClient,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
} from "@tanstack/react-query";
import {
  infiniteQueryOptions,
  useSuspenseInfiniteQuery,
} from "@tanstack/react-query";

export const getV1LicensesIdSuspenseInfiniteQueryKey = (
  id: GetV1LicensesIdPathParams["id"],
) => [{ url: "/v1/licenses/:id", params: { id: id } }] as const;

export type GetV1LicensesIdSuspenseInfiniteQueryKey = ReturnType<
  typeof getV1LicensesIdSuspenseInfiniteQueryKey
>;

/**
 * {@link /v1/licenses/:id}
 */
export async function getV1LicensesIdSuspenseInfinite(
  id: GetV1LicensesIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetV1LicensesIdQueryResponse,
    ResponseErrorConfig<GetV1LicensesId404>,
    unknown
  >({ method: "GET", url: `/v1/licenses/${id}`, ...requestConfig });
  return res.data;
}

export function getV1LicensesIdSuspenseInfiniteQueryOptions(
  id: GetV1LicensesIdPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const queryKey = getV1LicensesIdSuspenseInfiniteQueryKey(id);
  return infiniteQueryOptions<
    GetV1LicensesIdQueryResponse,
    ResponseErrorConfig<GetV1LicensesId404>,
    InfiniteData<GetV1LicensesIdQueryResponse>,
    typeof queryKey,
    number
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal;
      return getV1LicensesIdSuspenseInfinite(id, config);
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage, _allPages, lastPageParam) =>
      Array.isArray(lastPage) && lastPage.length === 0
        ? undefined
        : lastPageParam + 1,
    getPreviousPageParam: (_firstPage, _allPages, firstPageParam) =>
      firstPageParam <= 1 ? undefined : firstPageParam - 1,
  });
}

/**
 * {@link /v1/licenses/:id}
 */
export function useGetV1LicensesIdSuspenseInfinite<
  TQueryFnData = GetV1LicensesIdQueryResponse,
  TError = ResponseErrorConfig<GetV1LicensesId404>,
  TData = InfiniteData<TQueryFnData>,
  TQueryKey extends QueryKey = GetV1LicensesIdSuspenseInfiniteQueryKey,
  TPageParam = number,
>(
  id: GetV1LicensesIdPathParams["id"],
  options: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        TQueryFnData,
        TError,
        TData,
        TQueryKey,
        TPageParam
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...queryOptions } = queryConfig;
  const queryKey =
    queryOptions?.queryKey ?? getV1LicensesIdSuspenseInfiniteQueryKey(id);

  const query = useSuspenseInfiniteQuery(
    {
      ...getV1LicensesIdSuspenseInfiniteQueryOptions(id, config),
      queryKey,
      ...queryOptions,
    } as unknown as UseSuspenseInfiniteQueryOptions<
      TQueryFnData,
      TError,
      TData,
      TQueryKey,
      TPageParam
    >,
    queryClient,
  ) as UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
