/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  PutV1LicensesIdCapabilitiesCapabilityMutationRequest,
  PutV1LicensesIdCapabilitiesCapabilityMutationResponse,
  PutV1LicensesIdCapabilitiesCapabilityPathParams,
  PutV1LicensesIdCapabilitiesCapability400,
  PutV1LicensesIdCapabilitiesCapability404,
} from "../gen/PutV1LicensesIdCapabilitiesCapability.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const putV1LicensesIdCapabilitiesCapabilityMutationKey = () =>
  [{ url: "/v1/licenses/:id/capabilities/:capability" }] as const;

export type PutV1LicensesIdCapabilitiesCapabilityMutationKey = ReturnType<
  typeof putV1LicensesIdCapabilitiesCapabilityMutationKey
>;

/**
 * {@link /v1/licenses/:id/capabilities/:capability}
 */
export async function putV1LicensesIdCapabilitiesCapability(
  id: PutV1LicensesIdCapabilitiesCapabilityPathParams["id"],
  capability: PutV1LicensesIdCapabilitiesCapabilityPathParams["capability"],
  data: PutV1LicensesIdCapabilitiesCapabilityMutationRequest,
  config: Partial<
    RequestConfig<PutV1LicensesIdCapabilitiesCapabilityMutationRequest>
  > & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PutV1LicensesIdCapabilitiesCapabilityMutationResponse,
    ResponseErrorConfig<
      | PutV1LicensesIdCapabilitiesCapability400
      | PutV1LicensesIdCapabilitiesCapability404
    >,
    PutV1LicensesIdCapabilitiesCapabilityMutationRequest
  >({
    method: "PUT",
    url: `/v1/licenses/${id}/capabilities/${capability}`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function putV1LicensesIdCapabilitiesCapabilityMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<PutV1LicensesIdCapabilitiesCapabilityMutationRequest>
  > & { client?: typeof fetch } = {},
) {
  const mutationKey = putV1LicensesIdCapabilitiesCapabilityMutationKey();
  return mutationOptions<
    PutV1LicensesIdCapabilitiesCapabilityMutationResponse,
    ResponseErrorConfig<
      | PutV1LicensesIdCapabilitiesCapability400
      | PutV1LicensesIdCapabilitiesCapability404
    >,
    {
      id: PutV1LicensesIdCapabilitiesCapabilityPathParams["id"];
      capability: PutV1LicensesIdCapabilitiesCapabilityPathParams["capability"];
      data: PutV1LicensesIdCapabilitiesCapabilityMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, capability, data }) => {
      return putV1LicensesIdCapabilitiesCapability(
        id,
        capability,
        data,
        config,
      );
    },
  });
}

/**
 * {@link /v1/licenses/:id/capabilities/:capability}
 */
export function usePutV1LicensesIdCapabilitiesCapability<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PutV1LicensesIdCapabilitiesCapabilityMutationResponse,
      ResponseErrorConfig<
        | PutV1LicensesIdCapabilitiesCapability400
        | PutV1LicensesIdCapabilitiesCapability404
      >,
      {
        id: PutV1LicensesIdCapabilitiesCapabilityPathParams["id"];
        capability: PutV1LicensesIdCapabilitiesCapabilityPathParams["capability"];
        data: PutV1LicensesIdCapabilitiesCapabilityMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PutV1LicensesIdCapabilitiesCapabilityMutationRequest>
    > & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    putV1LicensesIdCapabilitiesCapabilityMutationKey();

  const baseOptions = putV1LicensesIdCapabilitiesCapabilityMutationOptions(
    config,
  ) as UseMutationOptions<
    PutV1LicensesIdCapabilitiesCapabilityMutationResponse,
    ResponseErrorConfig<
      | PutV1LicensesIdCapabilitiesCapability400
      | PutV1LicensesIdCapabilitiesCapability404
    >,
    {
      id: PutV1LicensesIdCapabilitiesCapabilityPathParams["id"];
      capability: PutV1LicensesIdCapabilitiesCapabilityPathParams["capability"];
      data: PutV1LicensesIdCapabilitiesCapabilityMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PutV1LicensesIdCapabilitiesCapabilityMutationResponse,
    ResponseErrorConfig<
      | PutV1LicensesIdCapabilitiesCapability400
      | PutV1LicensesIdCapabilitiesCapability404
    >,
    {
      id: PutV1LicensesIdCapabilitiesCapabilityPathParams["id"];
      capability: PutV1LicensesIdCapabilitiesCapabilityPathParams["capability"];
      data: PutV1LicensesIdCapabilitiesCapabilityMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PutV1LicensesIdCapabilitiesCapabilityMutationResponse,
    ResponseErrorConfig<
      | PutV1LicensesIdCapabilitiesCapability400
      | PutV1LicensesIdCapabilitiesCapability404
    >,
    {
      id: PutV1LicensesIdCapabilitiesCapabilityPathParams["id"];
      capability: PutV1LicensesIdCapabilitiesCapabilityPathParams["capability"];
      data: PutV1LicensesIdCapabilitiesCapabilityMutationRequest;
    },
    TContext
  >;
}
