/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  PostV1OrganizationsOrganizationidDevelopersMutationRequest,
  PostV1OrganizationsOrganizationidDevelopersMutationResponse,
  PostV1OrganizationsOrganizationidDevelopersPathParams,
  PostV1OrganizationsOrganizationidDevelopers400,
  PostV1OrganizationsOrganizationidDevelopers404,
} from "../gen/PostV1OrganizationsOrganizationidDevelopers.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postV1OrganizationsOrganizationidDevelopersMutationKey = () =>
  [{ url: "/v1/organizations/:organizationId/developers" }] as const;

export type PostV1OrganizationsOrganizationidDevelopersMutationKey = ReturnType<
  typeof postV1OrganizationsOrganizationidDevelopersMutationKey
>;

/**
 * {@link /v1/organizations/:organizationId/developers}
 */
export async function postV1OrganizationsOrganizationidDevelopers(
  organizationId: PostV1OrganizationsOrganizationidDevelopersPathParams["organizationId"],
  data: PostV1OrganizationsOrganizationidDevelopersMutationRequest,
  config: Partial<
    RequestConfig<PostV1OrganizationsOrganizationidDevelopersMutationRequest>
  > & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostV1OrganizationsOrganizationidDevelopersMutationResponse,
    ResponseErrorConfig<
      | PostV1OrganizationsOrganizationidDevelopers400
      | PostV1OrganizationsOrganizationidDevelopers404
    >,
    PostV1OrganizationsOrganizationidDevelopersMutationRequest
  >({
    method: "POST",
    url: `/v1/organizations/${organizationId}/developers`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function postV1OrganizationsOrganizationidDevelopersMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<PostV1OrganizationsOrganizationidDevelopersMutationRequest>
  > & { client?: typeof fetch } = {},
) {
  const mutationKey = postV1OrganizationsOrganizationidDevelopersMutationKey();
  return mutationOptions<
    PostV1OrganizationsOrganizationidDevelopersMutationResponse,
    ResponseErrorConfig<
      | PostV1OrganizationsOrganizationidDevelopers400
      | PostV1OrganizationsOrganizationidDevelopers404
    >,
    {
      organizationId: PostV1OrganizationsOrganizationidDevelopersPathParams["organizationId"];
      data: PostV1OrganizationsOrganizationidDevelopersMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ organizationId, data }) => {
      return postV1OrganizationsOrganizationidDevelopers(
        organizationId,
        data,
        config,
      );
    },
  });
}

/**
 * {@link /v1/organizations/:organizationId/developers}
 */
export function usePostV1OrganizationsOrganizationidDevelopers<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1OrganizationsOrganizationidDevelopersMutationResponse,
      ResponseErrorConfig<
        | PostV1OrganizationsOrganizationidDevelopers400
        | PostV1OrganizationsOrganizationidDevelopers404
      >,
      {
        organizationId: PostV1OrganizationsOrganizationidDevelopersPathParams["organizationId"];
        data: PostV1OrganizationsOrganizationidDevelopersMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostV1OrganizationsOrganizationidDevelopersMutationRequest>
    > & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    postV1OrganizationsOrganizationidDevelopersMutationKey();

  const baseOptions =
    postV1OrganizationsOrganizationidDevelopersMutationOptions(
      config,
    ) as UseMutationOptions<
      PostV1OrganizationsOrganizationidDevelopersMutationResponse,
      ResponseErrorConfig<
        | PostV1OrganizationsOrganizationidDevelopers400
        | PostV1OrganizationsOrganizationidDevelopers404
      >,
      {
        organizationId: PostV1OrganizationsOrganizationidDevelopersPathParams["organizationId"];
        data: PostV1OrganizationsOrganizationidDevelopersMutationRequest;
      },
      TContext
    >;

  return useMutation<
    PostV1OrganizationsOrganizationidDevelopersMutationResponse,
    ResponseErrorConfig<
      | PostV1OrganizationsOrganizationidDevelopers400
      | PostV1OrganizationsOrganizationidDevelopers404
    >,
    {
      organizationId: PostV1OrganizationsOrganizationidDevelopersPathParams["organizationId"];
      data: PostV1OrganizationsOrganizationidDevelopersMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostV1OrganizationsOrganizationidDevelopersMutationResponse,
    ResponseErrorConfig<
      | PostV1OrganizationsOrganizationidDevelopers400
      | PostV1OrganizationsOrganizationidDevelopers404
    >,
    {
      organizationId: PostV1OrganizationsOrganizationidDevelopersPathParams["organizationId"];
      data: PostV1OrganizationsOrganizationidDevelopersMutationRequest;
    },
    TContext
  >;
}
