/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  PostV1LicensesIdPackagesMutationRequest,
  PostV1LicensesIdPackagesMutationResponse,
  PostV1LicensesIdPackagesPathParams,
  PostV1LicensesIdPackages400,
  PostV1LicensesIdPackages404,
} from "../gen/PostV1LicensesIdPackages.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postV1LicensesIdPackagesMutationKey = () =>
  [{ url: "/v1/licenses/:id/packages" }] as const;

export type PostV1LicensesIdPackagesMutationKey = ReturnType<
  typeof postV1LicensesIdPackagesMutationKey
>;

/**
 * {@link /v1/licenses/:id/packages}
 */
export async function postV1LicensesIdPackages(
  id: PostV1LicensesIdPackagesPathParams["id"],
  data: PostV1LicensesIdPackagesMutationRequest,
  config: Partial<RequestConfig<PostV1LicensesIdPackagesMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostV1LicensesIdPackagesMutationResponse,
    ResponseErrorConfig<
      PostV1LicensesIdPackages400 | PostV1LicensesIdPackages404
    >,
    PostV1LicensesIdPackagesMutationRequest
  >({
    method: "POST",
    url: `/v1/licenses/${id}/packages`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function postV1LicensesIdPackagesMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostV1LicensesIdPackagesMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = postV1LicensesIdPackagesMutationKey();
  return mutationOptions<
    PostV1LicensesIdPackagesMutationResponse,
    ResponseErrorConfig<
      PostV1LicensesIdPackages400 | PostV1LicensesIdPackages404
    >,
    {
      id: PostV1LicensesIdPackagesPathParams["id"];
      data: PostV1LicensesIdPackagesMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return postV1LicensesIdPackages(id, data, config);
    },
  });
}

/**
 * {@link /v1/licenses/:id/packages}
 */
export function usePostV1LicensesIdPackages<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1LicensesIdPackagesMutationResponse,
      ResponseErrorConfig<
        PostV1LicensesIdPackages400 | PostV1LicensesIdPackages404
      >,
      {
        id: PostV1LicensesIdPackagesPathParams["id"];
        data: PostV1LicensesIdPackagesMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostV1LicensesIdPackagesMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postV1LicensesIdPackagesMutationKey();

  const baseOptions = postV1LicensesIdPackagesMutationOptions(
    config,
  ) as UseMutationOptions<
    PostV1LicensesIdPackagesMutationResponse,
    ResponseErrorConfig<
      PostV1LicensesIdPackages400 | PostV1LicensesIdPackages404
    >,
    {
      id: PostV1LicensesIdPackagesPathParams["id"];
      data: PostV1LicensesIdPackagesMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PostV1LicensesIdPackagesMutationResponse,
    ResponseErrorConfig<
      PostV1LicensesIdPackages400 | PostV1LicensesIdPackages404
    >,
    {
      id: PostV1LicensesIdPackagesPathParams["id"];
      data: PostV1LicensesIdPackagesMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostV1LicensesIdPackagesMutationResponse,
    ResponseErrorConfig<
      PostV1LicensesIdPackages400 | PostV1LicensesIdPackages404
    >,
    {
      id: PostV1LicensesIdPackagesPathParams["id"];
      data: PostV1LicensesIdPackagesMutationRequest;
    },
    TContext
  >;
}
