/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  PatchV1ApiKeysIdMutationRequest,
  PatchV1ApiKeysIdMutationResponse,
  PatchV1ApiKeysIdPathParams,
  PatchV1ApiKeysId400,
  PatchV1ApiKeysId404,
} from "../gen/PatchV1ApiKeysId.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const patchV1ApiKeysIdMutationKey = () =>
  [{ url: "/v1/api-keys/:id" }] as const;

export type PatchV1ApiKeysIdMutationKey = ReturnType<
  typeof patchV1ApiKeysIdMutationKey
>;

/**
 * {@link /v1/api-keys/:id}
 */
export async function patchV1ApiKeysId(
  id: PatchV1ApiKeysIdPathParams["id"],
  data?: PatchV1ApiKeysIdMutationRequest,
  config: Partial<RequestConfig<PatchV1ApiKeysIdMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchV1ApiKeysIdMutationResponse,
    ResponseErrorConfig<PatchV1ApiKeysId400 | PatchV1ApiKeysId404>,
    PatchV1ApiKeysIdMutationRequest
  >({
    method: "PATCH",
    url: `/v1/api-keys/${id}`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function patchV1ApiKeysIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PatchV1ApiKeysIdMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = patchV1ApiKeysIdMutationKey();
  return mutationOptions<
    PatchV1ApiKeysIdMutationResponse,
    ResponseErrorConfig<PatchV1ApiKeysId400 | PatchV1ApiKeysId404>,
    {
      id: PatchV1ApiKeysIdPathParams["id"];
      data?: PatchV1ApiKeysIdMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return patchV1ApiKeysId(id, data, config);
    },
  });
}

/**
 * {@link /v1/api-keys/:id}
 */
export function usePatchV1ApiKeysId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchV1ApiKeysIdMutationResponse,
      ResponseErrorConfig<PatchV1ApiKeysId400 | PatchV1ApiKeysId404>,
      {
        id: PatchV1ApiKeysIdPathParams["id"];
        data?: PatchV1ApiKeysIdMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PatchV1ApiKeysIdMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? patchV1ApiKeysIdMutationKey();

  const baseOptions = patchV1ApiKeysIdMutationOptions(
    config,
  ) as UseMutationOptions<
    PatchV1ApiKeysIdMutationResponse,
    ResponseErrorConfig<PatchV1ApiKeysId400 | PatchV1ApiKeysId404>,
    {
      id: PatchV1ApiKeysIdPathParams["id"];
      data?: PatchV1ApiKeysIdMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PatchV1ApiKeysIdMutationResponse,
    ResponseErrorConfig<PatchV1ApiKeysId400 | PatchV1ApiKeysId404>,
    {
      id: PatchV1ApiKeysIdPathParams["id"];
      data?: PatchV1ApiKeysIdMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PatchV1ApiKeysIdMutationResponse,
    ResponseErrorConfig<PatchV1ApiKeysId400 | PatchV1ApiKeysId404>,
    {
      id: PatchV1ApiKeysIdPathParams["id"];
      data?: PatchV1ApiKeysIdMutationRequest;
    },
    TContext
  >;
}
