/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  PostV1LicensesIdSuspendMutationResponse,
  PostV1LicensesIdSuspendPathParams,
  PostV1LicensesIdSuspend404,
} from "../gen/PostV1LicensesIdSuspend.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postV1LicensesIdSuspendMutationKey = () =>
  [{ url: "/v1/licenses/:id/suspend" }] as const;

export type PostV1LicensesIdSuspendMutationKey = ReturnType<
  typeof postV1LicensesIdSuspendMutationKey
>;

/**
 * {@link /v1/licenses/:id/suspend}
 */
export async function postV1LicensesIdSuspend(
  id: PostV1LicensesIdSuspendPathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostV1LicensesIdSuspendMutationResponse,
    ResponseErrorConfig<PostV1LicensesIdSuspend404>,
    unknown
  >({ method: "POST", url: `/v1/licenses/${id}/suspend`, ...requestConfig });
  return res.data;
}

export function postV1LicensesIdSuspendMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = postV1LicensesIdSuspendMutationKey();
  return mutationOptions<
    PostV1LicensesIdSuspendMutationResponse,
    ResponseErrorConfig<PostV1LicensesIdSuspend404>,
    { id: PostV1LicensesIdSuspendPathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return postV1LicensesIdSuspend(id, config);
    },
  });
}

/**
 * {@link /v1/licenses/:id/suspend}
 */
export function usePostV1LicensesIdSuspend<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1LicensesIdSuspendMutationResponse,
      ResponseErrorConfig<PostV1LicensesIdSuspend404>,
      { id: PostV1LicensesIdSuspendPathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postV1LicensesIdSuspendMutationKey();

  const baseOptions = postV1LicensesIdSuspendMutationOptions(
    config,
  ) as UseMutationOptions<
    PostV1LicensesIdSuspendMutationResponse,
    ResponseErrorConfig<PostV1LicensesIdSuspend404>,
    { id: PostV1LicensesIdSuspendPathParams["id"] },
    TContext
  >;

  return useMutation<
    PostV1LicensesIdSuspendMutationResponse,
    ResponseErrorConfig<PostV1LicensesIdSuspend404>,
    { id: PostV1LicensesIdSuspendPathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostV1LicensesIdSuspendMutationResponse,
    ResponseErrorConfig<PostV1LicensesIdSuspend404>,
    { id: PostV1LicensesIdSuspendPathParams["id"] },
    TContext
  >;
}
