/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  PostV1ApiKeysIdRevokeMutationResponse,
  PostV1ApiKeysIdRevokePathParams,
  PostV1ApiKeysIdRevoke404,
} from "../gen/PostV1ApiKeysIdRevoke.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postV1ApiKeysIdRevokeMutationKey = () =>
  [{ url: "/v1/api-keys/:id/revoke" }] as const;

export type PostV1ApiKeysIdRevokeMutationKey = ReturnType<
  typeof postV1ApiKeysIdRevokeMutationKey
>;

/**
 * {@link /v1/api-keys/:id/revoke}
 */
export async function postV1ApiKeysIdRevoke(
  id: PostV1ApiKeysIdRevokePathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostV1ApiKeysIdRevokeMutationResponse,
    ResponseErrorConfig<PostV1ApiKeysIdRevoke404>,
    unknown
  >({ method: "POST", url: `/v1/api-keys/${id}/revoke`, ...requestConfig });
  return res.data;
}

export function postV1ApiKeysIdRevokeMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = postV1ApiKeysIdRevokeMutationKey();
  return mutationOptions<
    PostV1ApiKeysIdRevokeMutationResponse,
    ResponseErrorConfig<PostV1ApiKeysIdRevoke404>,
    { id: PostV1ApiKeysIdRevokePathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return postV1ApiKeysIdRevoke(id, config);
    },
  });
}

/**
 * {@link /v1/api-keys/:id/revoke}
 */
export function usePostV1ApiKeysIdRevoke<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1ApiKeysIdRevokeMutationResponse,
      ResponseErrorConfig<PostV1ApiKeysIdRevoke404>,
      { id: PostV1ApiKeysIdRevokePathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postV1ApiKeysIdRevokeMutationKey();

  const baseOptions = postV1ApiKeysIdRevokeMutationOptions(
    config,
  ) as UseMutationOptions<
    PostV1ApiKeysIdRevokeMutationResponse,
    ResponseErrorConfig<PostV1ApiKeysIdRevoke404>,
    { id: PostV1ApiKeysIdRevokePathParams["id"] },
    TContext
  >;

  return useMutation<
    PostV1ApiKeysIdRevokeMutationResponse,
    ResponseErrorConfig<PostV1ApiKeysIdRevoke404>,
    { id: PostV1ApiKeysIdRevokePathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostV1ApiKeysIdRevokeMutationResponse,
    ResponseErrorConfig<PostV1ApiKeysIdRevoke404>,
    { id: PostV1ApiKeysIdRevokePathParams["id"] },
    TContext
  >;
}
