/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  PostV1CapabilitiesResolveMutationRequest,
  PostV1CapabilitiesResolveMutationResponse,
  PostV1CapabilitiesResolve401,
} from "../gen/PostV1CapabilitiesResolve.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postV1CapabilitiesResolveMutationKey = () =>
  [{ url: "/v1/capabilities/resolve" }] as const;

export type PostV1CapabilitiesResolveMutationKey = ReturnType<
  typeof postV1CapabilitiesResolveMutationKey
>;

/**
 * {@link /v1/capabilities/resolve}
 */
export async function postV1CapabilitiesResolve(
  data: PostV1CapabilitiesResolveMutationRequest,
  config: Partial<RequestConfig<PostV1CapabilitiesResolveMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostV1CapabilitiesResolveMutationResponse,
    ResponseErrorConfig<PostV1CapabilitiesResolve401>,
    PostV1CapabilitiesResolveMutationRequest
  >({
    method: "POST",
    url: `/v1/capabilities/resolve`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function postV1CapabilitiesResolveMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostV1CapabilitiesResolveMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = postV1CapabilitiesResolveMutationKey();
  return mutationOptions<
    PostV1CapabilitiesResolveMutationResponse,
    ResponseErrorConfig<PostV1CapabilitiesResolve401>,
    { data: PostV1CapabilitiesResolveMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postV1CapabilitiesResolve(data, config);
    },
  });
}

/**
 * {@link /v1/capabilities/resolve}
 */
export function usePostV1CapabilitiesResolve<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1CapabilitiesResolveMutationResponse,
      ResponseErrorConfig<PostV1CapabilitiesResolve401>,
      { data: PostV1CapabilitiesResolveMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostV1CapabilitiesResolveMutationRequest>
    > & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postV1CapabilitiesResolveMutationKey();

  const baseOptions = postV1CapabilitiesResolveMutationOptions(
    config,
  ) as UseMutationOptions<
    PostV1CapabilitiesResolveMutationResponse,
    ResponseErrorConfig<PostV1CapabilitiesResolve401>,
    { data: PostV1CapabilitiesResolveMutationRequest },
    TContext
  >;

  return useMutation<
    PostV1CapabilitiesResolveMutationResponse,
    ResponseErrorConfig<PostV1CapabilitiesResolve401>,
    { data: PostV1CapabilitiesResolveMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostV1CapabilitiesResolveMutationResponse,
    ResponseErrorConfig<PostV1CapabilitiesResolve401>,
    { data: PostV1CapabilitiesResolveMutationRequest },
    TContext
  >;
}
