/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  PostV1LicensesIdActivateMutationResponse,
  PostV1LicensesIdActivatePathParams,
  PostV1LicensesIdActivate404,
} from "../gen/PostV1LicensesIdActivate.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postV1LicensesIdActivateMutationKey = () =>
  [{ url: "/v1/licenses/:id/activate" }] as const;

export type PostV1LicensesIdActivateMutationKey = ReturnType<
  typeof postV1LicensesIdActivateMutationKey
>;

/**
 * {@link /v1/licenses/:id/activate}
 */
export async function postV1LicensesIdActivate(
  id: PostV1LicensesIdActivatePathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostV1LicensesIdActivateMutationResponse,
    ResponseErrorConfig<PostV1LicensesIdActivate404>,
    unknown
  >({ method: "POST", url: `/v1/licenses/${id}/activate`, ...requestConfig });
  return res.data;
}

export function postV1LicensesIdActivateMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = postV1LicensesIdActivateMutationKey();
  return mutationOptions<
    PostV1LicensesIdActivateMutationResponse,
    ResponseErrorConfig<PostV1LicensesIdActivate404>,
    { id: PostV1LicensesIdActivatePathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return postV1LicensesIdActivate(id, config);
    },
  });
}

/**
 * {@link /v1/licenses/:id/activate}
 */
export function usePostV1LicensesIdActivate<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1LicensesIdActivateMutationResponse,
      ResponseErrorConfig<PostV1LicensesIdActivate404>,
      { id: PostV1LicensesIdActivatePathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postV1LicensesIdActivateMutationKey();

  const baseOptions = postV1LicensesIdActivateMutationOptions(
    config,
  ) as UseMutationOptions<
    PostV1LicensesIdActivateMutationResponse,
    ResponseErrorConfig<PostV1LicensesIdActivate404>,
    { id: PostV1LicensesIdActivatePathParams["id"] },
    TContext
  >;

  return useMutation<
    PostV1LicensesIdActivateMutationResponse,
    ResponseErrorConfig<PostV1LicensesIdActivate404>,
    { id: PostV1LicensesIdActivatePathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostV1LicensesIdActivateMutationResponse,
    ResponseErrorConfig<PostV1LicensesIdActivate404>,
    { id: PostV1LicensesIdActivatePathParams["id"] },
    TContext
  >;
}
