/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  PostV1OrganizationsOrganizationidApiKeysMutationRequest,
  PostV1OrganizationsOrganizationidApiKeysMutationResponse,
  PostV1OrganizationsOrganizationidApiKeysPathParams,
  PostV1OrganizationsOrganizationidApiKeys400,
  PostV1OrganizationsOrganizationidApiKeys404,
} from "../gen/PostV1OrganizationsOrganizationidApiKeys.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postV1OrganizationsOrganizationidApiKeysMutationKey = () =>
  [{ url: "/v1/organizations/:organizationId/api-keys" }] as const;

export type PostV1OrganizationsOrganizationidApiKeysMutationKey = ReturnType<
  typeof postV1OrganizationsOrganizationidApiKeysMutationKey
>;

/**
 * {@link /v1/organizations/:organizationId/api-keys}
 */
export async function postV1OrganizationsOrganizationidApiKeys(
  organizationId: PostV1OrganizationsOrganizationidApiKeysPathParams["organizationId"],
  data: PostV1OrganizationsOrganizationidApiKeysMutationRequest,
  config: Partial<
    RequestConfig<PostV1OrganizationsOrganizationidApiKeysMutationRequest>
  > & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostV1OrganizationsOrganizationidApiKeysMutationResponse,
    ResponseErrorConfig<
      | PostV1OrganizationsOrganizationidApiKeys400
      | PostV1OrganizationsOrganizationidApiKeys404
    >,
    PostV1OrganizationsOrganizationidApiKeysMutationRequest
  >({
    method: "POST",
    url: `/v1/organizations/${organizationId}/api-keys`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function postV1OrganizationsOrganizationidApiKeysMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<PostV1OrganizationsOrganizationidApiKeysMutationRequest>
  > & { client?: typeof fetch } = {},
) {
  const mutationKey = postV1OrganizationsOrganizationidApiKeysMutationKey();
  return mutationOptions<
    PostV1OrganizationsOrganizationidApiKeysMutationResponse,
    ResponseErrorConfig<
      | PostV1OrganizationsOrganizationidApiKeys400
      | PostV1OrganizationsOrganizationidApiKeys404
    >,
    {
      organizationId: PostV1OrganizationsOrganizationidApiKeysPathParams["organizationId"];
      data: PostV1OrganizationsOrganizationidApiKeysMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ organizationId, data }) => {
      return postV1OrganizationsOrganizationidApiKeys(
        organizationId,
        data,
        config,
      );
    },
  });
}

/**
 * {@link /v1/organizations/:organizationId/api-keys}
 */
export function usePostV1OrganizationsOrganizationidApiKeys<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1OrganizationsOrganizationidApiKeysMutationResponse,
      ResponseErrorConfig<
        | PostV1OrganizationsOrganizationidApiKeys400
        | PostV1OrganizationsOrganizationidApiKeys404
      >,
      {
        organizationId: PostV1OrganizationsOrganizationidApiKeysPathParams["organizationId"];
        data: PostV1OrganizationsOrganizationidApiKeysMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostV1OrganizationsOrganizationidApiKeysMutationRequest>
    > & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    postV1OrganizationsOrganizationidApiKeysMutationKey();

  const baseOptions = postV1OrganizationsOrganizationidApiKeysMutationOptions(
    config,
  ) as UseMutationOptions<
    PostV1OrganizationsOrganizationidApiKeysMutationResponse,
    ResponseErrorConfig<
      | PostV1OrganizationsOrganizationidApiKeys400
      | PostV1OrganizationsOrganizationidApiKeys404
    >,
    {
      organizationId: PostV1OrganizationsOrganizationidApiKeysPathParams["organizationId"];
      data: PostV1OrganizationsOrganizationidApiKeysMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PostV1OrganizationsOrganizationidApiKeysMutationResponse,
    ResponseErrorConfig<
      | PostV1OrganizationsOrganizationidApiKeys400
      | PostV1OrganizationsOrganizationidApiKeys404
    >,
    {
      organizationId: PostV1OrganizationsOrganizationidApiKeysPathParams["organizationId"];
      data: PostV1OrganizationsOrganizationidApiKeysMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostV1OrganizationsOrganizationidApiKeysMutationResponse,
    ResponseErrorConfig<
      | PostV1OrganizationsOrganizationidApiKeys400
      | PostV1OrganizationsOrganizationidApiKeys404
    >,
    {
      organizationId: PostV1OrganizationsOrganizationidApiKeysPathParams["organizationId"];
      data: PostV1OrganizationsOrganizationidApiKeysMutationRequest;
    },
    TContext
  >;
}
