/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  PostV1OrganizationsMutationRequest,
  PostV1OrganizationsMutationResponse,
  PostV1Organizations400,
  PostV1Organizations409,
} from "../gen/PostV1Organizations.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postV1OrganizationsMutationKey = () =>
  [{ url: "/v1/organizations" }] as const;

export type PostV1OrganizationsMutationKey = ReturnType<
  typeof postV1OrganizationsMutationKey
>;

/**
 * {@link /v1/organizations}
 */
export async function postV1Organizations(
  data: PostV1OrganizationsMutationRequest,
  config: Partial<RequestConfig<PostV1OrganizationsMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostV1OrganizationsMutationResponse,
    ResponseErrorConfig<PostV1Organizations400 | PostV1Organizations409>,
    PostV1OrganizationsMutationRequest
  >({
    method: "POST",
    url: `/v1/organizations`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function postV1OrganizationsMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostV1OrganizationsMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = postV1OrganizationsMutationKey();
  return mutationOptions<
    PostV1OrganizationsMutationResponse,
    ResponseErrorConfig<PostV1Organizations400 | PostV1Organizations409>,
    { data: PostV1OrganizationsMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postV1Organizations(data, config);
    },
  });
}

/**
 * {@link /v1/organizations}
 */
export function usePostV1Organizations<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1OrganizationsMutationResponse,
      ResponseErrorConfig<PostV1Organizations400 | PostV1Organizations409>,
      { data: PostV1OrganizationsMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostV1OrganizationsMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postV1OrganizationsMutationKey();

  const baseOptions = postV1OrganizationsMutationOptions(
    config,
  ) as UseMutationOptions<
    PostV1OrganizationsMutationResponse,
    ResponseErrorConfig<PostV1Organizations400 | PostV1Organizations409>,
    { data: PostV1OrganizationsMutationRequest },
    TContext
  >;

  return useMutation<
    PostV1OrganizationsMutationResponse,
    ResponseErrorConfig<PostV1Organizations400 | PostV1Organizations409>,
    { data: PostV1OrganizationsMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostV1OrganizationsMutationResponse,
    ResponseErrorConfig<PostV1Organizations400 | PostV1Organizations409>,
    { data: PostV1OrganizationsMutationRequest },
    TContext
  >;
}
