/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  PostV1PackagesDownloadMutationRequest,
  PostV1PackagesDownloadMutationResponse,
  PostV1PackagesDownload401,
  PostV1PackagesDownload404,
} from "../gen/PostV1PackagesDownload.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postV1PackagesDownloadMutationKey = () =>
  [{ url: "/v1/packages/download" }] as const;

export type PostV1PackagesDownloadMutationKey = ReturnType<
  typeof postV1PackagesDownloadMutationKey
>;

/**
 * {@link /v1/packages/download}
 */
export async function postV1PackagesDownload(
  data: PostV1PackagesDownloadMutationRequest,
  config: Partial<RequestConfig<PostV1PackagesDownloadMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostV1PackagesDownloadMutationResponse,
    ResponseErrorConfig<PostV1PackagesDownload401 | PostV1PackagesDownload404>,
    PostV1PackagesDownloadMutationRequest
  >({
    method: "POST",
    url: `/v1/packages/download`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function postV1PackagesDownloadMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PostV1PackagesDownloadMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = postV1PackagesDownloadMutationKey();
  return mutationOptions<
    PostV1PackagesDownloadMutationResponse,
    ResponseErrorConfig<PostV1PackagesDownload401 | PostV1PackagesDownload404>,
    { data: PostV1PackagesDownloadMutationRequest },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ data }) => {
      return postV1PackagesDownload(data, config);
    },
  });
}

/**
 * {@link /v1/packages/download}
 */
export function usePostV1PackagesDownload<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1PackagesDownloadMutationResponse,
      ResponseErrorConfig<
        PostV1PackagesDownload401 | PostV1PackagesDownload404
      >,
      { data: PostV1PackagesDownloadMutationRequest },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PostV1PackagesDownloadMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postV1PackagesDownloadMutationKey();

  const baseOptions = postV1PackagesDownloadMutationOptions(
    config,
  ) as UseMutationOptions<
    PostV1PackagesDownloadMutationResponse,
    ResponseErrorConfig<PostV1PackagesDownload401 | PostV1PackagesDownload404>,
    { data: PostV1PackagesDownloadMutationRequest },
    TContext
  >;

  return useMutation<
    PostV1PackagesDownloadMutationResponse,
    ResponseErrorConfig<PostV1PackagesDownload401 | PostV1PackagesDownload404>,
    { data: PostV1PackagesDownloadMutationRequest },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostV1PackagesDownloadMutationResponse,
    ResponseErrorConfig<PostV1PackagesDownload401 | PostV1PackagesDownload404>,
    { data: PostV1PackagesDownloadMutationRequest },
    TContext
  >;
}
