/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  PatchV1OrganizationsIdMutationRequest,
  PatchV1OrganizationsIdMutationResponse,
  PatchV1OrganizationsIdPathParams,
  PatchV1OrganizationsId404,
} from "../gen/PatchV1OrganizationsId.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const patchV1OrganizationsIdMutationKey = () =>
  [{ url: "/v1/organizations/:id" }] as const;

export type PatchV1OrganizationsIdMutationKey = ReturnType<
  typeof patchV1OrganizationsIdMutationKey
>;

/**
 * {@link /v1/organizations/:id}
 */
export async function patchV1OrganizationsId(
  id: PatchV1OrganizationsIdPathParams["id"],
  data?: PatchV1OrganizationsIdMutationRequest,
  config: Partial<RequestConfig<PatchV1OrganizationsIdMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchV1OrganizationsIdMutationResponse,
    ResponseErrorConfig<PatchV1OrganizationsId404>,
    PatchV1OrganizationsIdMutationRequest
  >({
    method: "PATCH",
    url: `/v1/organizations/${id}`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function patchV1OrganizationsIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PatchV1OrganizationsIdMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = patchV1OrganizationsIdMutationKey();
  return mutationOptions<
    PatchV1OrganizationsIdMutationResponse,
    ResponseErrorConfig<PatchV1OrganizationsId404>,
    {
      id: PatchV1OrganizationsIdPathParams["id"];
      data?: PatchV1OrganizationsIdMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return patchV1OrganizationsId(id, data, config);
    },
  });
}

/**
 * {@link /v1/organizations/:id}
 */
export function usePatchV1OrganizationsId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchV1OrganizationsIdMutationResponse,
      ResponseErrorConfig<PatchV1OrganizationsId404>,
      {
        id: PatchV1OrganizationsIdPathParams["id"];
        data?: PatchV1OrganizationsIdMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PatchV1OrganizationsIdMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? patchV1OrganizationsIdMutationKey();

  const baseOptions = patchV1OrganizationsIdMutationOptions(
    config,
  ) as UseMutationOptions<
    PatchV1OrganizationsIdMutationResponse,
    ResponseErrorConfig<PatchV1OrganizationsId404>,
    {
      id: PatchV1OrganizationsIdPathParams["id"];
      data?: PatchV1OrganizationsIdMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PatchV1OrganizationsIdMutationResponse,
    ResponseErrorConfig<PatchV1OrganizationsId404>,
    {
      id: PatchV1OrganizationsIdPathParams["id"];
      data?: PatchV1OrganizationsIdMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PatchV1OrganizationsIdMutationResponse,
    ResponseErrorConfig<PatchV1OrganizationsId404>,
    {
      id: PatchV1OrganizationsIdPathParams["id"];
      data?: PatchV1OrganizationsIdMutationRequest;
    },
    TContext
  >;
}
