/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  PostV1OrganizationsOrganizationidLicensesMutationRequest,
  PostV1OrganizationsOrganizationidLicensesMutationResponse,
  PostV1OrganizationsOrganizationidLicensesPathParams,
  PostV1OrganizationsOrganizationidLicenses400,
  PostV1OrganizationsOrganizationidLicenses404,
} from "../gen/PostV1OrganizationsOrganizationidLicenses.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postV1OrganizationsOrganizationidLicensesMutationKey = () =>
  [{ url: "/v1/organizations/:organizationId/licenses" }] as const;

export type PostV1OrganizationsOrganizationidLicensesMutationKey = ReturnType<
  typeof postV1OrganizationsOrganizationidLicensesMutationKey
>;

/**
 * {@link /v1/organizations/:organizationId/licenses}
 */
export async function postV1OrganizationsOrganizationidLicenses(
  organizationId: PostV1OrganizationsOrganizationidLicensesPathParams["organizationId"],
  data: PostV1OrganizationsOrganizationidLicensesMutationRequest,
  config: Partial<
    RequestConfig<PostV1OrganizationsOrganizationidLicensesMutationRequest>
  > & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PostV1OrganizationsOrganizationidLicensesMutationResponse,
    ResponseErrorConfig<
      | PostV1OrganizationsOrganizationidLicenses400
      | PostV1OrganizationsOrganizationidLicenses404
    >,
    PostV1OrganizationsOrganizationidLicensesMutationRequest
  >({
    method: "POST",
    url: `/v1/organizations/${organizationId}/licenses`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function postV1OrganizationsOrganizationidLicensesMutationOptions<
  TContext = unknown,
>(
  config: Partial<
    RequestConfig<PostV1OrganizationsOrganizationidLicensesMutationRequest>
  > & { client?: typeof fetch } = {},
) {
  const mutationKey = postV1OrganizationsOrganizationidLicensesMutationKey();
  return mutationOptions<
    PostV1OrganizationsOrganizationidLicensesMutationResponse,
    ResponseErrorConfig<
      | PostV1OrganizationsOrganizationidLicenses400
      | PostV1OrganizationsOrganizationidLicenses404
    >,
    {
      organizationId: PostV1OrganizationsOrganizationidLicensesPathParams["organizationId"];
      data: PostV1OrganizationsOrganizationidLicensesMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ organizationId, data }) => {
      return postV1OrganizationsOrganizationidLicenses(
        organizationId,
        data,
        config,
      );
    },
  });
}

/**
 * {@link /v1/organizations/:organizationId/licenses}
 */
export function usePostV1OrganizationsOrganizationidLicenses<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1OrganizationsOrganizationidLicensesMutationResponse,
      ResponseErrorConfig<
        | PostV1OrganizationsOrganizationidLicenses400
        | PostV1OrganizationsOrganizationidLicenses404
      >,
      {
        organizationId: PostV1OrganizationsOrganizationidLicensesPathParams["organizationId"];
        data: PostV1OrganizationsOrganizationidLicensesMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<
      RequestConfig<PostV1OrganizationsOrganizationidLicensesMutationRequest>
    > & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ??
    postV1OrganizationsOrganizationidLicensesMutationKey();

  const baseOptions = postV1OrganizationsOrganizationidLicensesMutationOptions(
    config,
  ) as UseMutationOptions<
    PostV1OrganizationsOrganizationidLicensesMutationResponse,
    ResponseErrorConfig<
      | PostV1OrganizationsOrganizationidLicenses400
      | PostV1OrganizationsOrganizationidLicenses404
    >,
    {
      organizationId: PostV1OrganizationsOrganizationidLicensesPathParams["organizationId"];
      data: PostV1OrganizationsOrganizationidLicensesMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PostV1OrganizationsOrganizationidLicensesMutationResponse,
    ResponseErrorConfig<
      | PostV1OrganizationsOrganizationidLicenses400
      | PostV1OrganizationsOrganizationidLicenses404
    >,
    {
      organizationId: PostV1OrganizationsOrganizationidLicensesPathParams["organizationId"];
      data: PostV1OrganizationsOrganizationidLicensesMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostV1OrganizationsOrganizationidLicensesMutationResponse,
    ResponseErrorConfig<
      | PostV1OrganizationsOrganizationidLicenses400
      | PostV1OrganizationsOrganizationidLicenses404
    >,
    {
      organizationId: PostV1OrganizationsOrganizationidLicensesPathParams["organizationId"];
      data: PostV1OrganizationsOrganizationidLicensesMutationRequest;
    },
    TContext
  >;
}
