/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  PostV1LicensesIdRevokeMutationResponse,
  PostV1LicensesIdRevokePathParams,
  PostV1LicensesIdRevoke404,
} from "../gen/PostV1LicensesIdRevoke.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const postV1LicensesIdRevokeMutationKey = () =>
  [{ url: "/v1/licenses/:id/revoke" }] as const;

export type PostV1LicensesIdRevokeMutationKey = ReturnType<
  typeof postV1LicensesIdRevokeMutationKey
>;

/**
 * {@link /v1/licenses/:id/revoke}
 */
export async function postV1LicensesIdRevoke(
  id: PostV1LicensesIdRevokePathParams["id"],
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    PostV1LicensesIdRevokeMutationResponse,
    ResponseErrorConfig<PostV1LicensesIdRevoke404>,
    unknown
  >({ method: "POST", url: `/v1/licenses/${id}/revoke`, ...requestConfig });
  return res.data;
}

export function postV1LicensesIdRevokeMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig> & { client?: typeof fetch } = {},
) {
  const mutationKey = postV1LicensesIdRevokeMutationKey();
  return mutationOptions<
    PostV1LicensesIdRevokeMutationResponse,
    ResponseErrorConfig<PostV1LicensesIdRevoke404>,
    { id: PostV1LicensesIdRevokePathParams["id"] },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id }) => {
      return postV1LicensesIdRevoke(id, config);
    },
  });
}

/**
 * {@link /v1/licenses/:id/revoke}
 */
export function usePostV1LicensesIdRevoke<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostV1LicensesIdRevokeMutationResponse,
      ResponseErrorConfig<PostV1LicensesIdRevoke404>,
      { id: PostV1LicensesIdRevokePathParams["id"] },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: typeof fetch };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? postV1LicensesIdRevokeMutationKey();

  const baseOptions = postV1LicensesIdRevokeMutationOptions(
    config,
  ) as UseMutationOptions<
    PostV1LicensesIdRevokeMutationResponse,
    ResponseErrorConfig<PostV1LicensesIdRevoke404>,
    { id: PostV1LicensesIdRevokePathParams["id"] },
    TContext
  >;

  return useMutation<
    PostV1LicensesIdRevokeMutationResponse,
    ResponseErrorConfig<PostV1LicensesIdRevoke404>,
    { id: PostV1LicensesIdRevokePathParams["id"] },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PostV1LicensesIdRevokeMutationResponse,
    ResponseErrorConfig<PostV1LicensesIdRevoke404>,
    { id: PostV1LicensesIdRevokePathParams["id"] },
    TContext
  >;
}
