/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  PatchV1DevelopersIdMutationRequest,
  PatchV1DevelopersIdMutationResponse,
  PatchV1DevelopersIdPathParams,
  PatchV1DevelopersId400,
  PatchV1DevelopersId404,
} from "../gen/PatchV1DevelopersId.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const patchV1DevelopersIdMutationKey = () =>
  [{ url: "/v1/developers/:id" }] as const;

export type PatchV1DevelopersIdMutationKey = ReturnType<
  typeof patchV1DevelopersIdMutationKey
>;

/**
 * {@link /v1/developers/:id}
 */
export async function patchV1DevelopersId(
  id: PatchV1DevelopersIdPathParams["id"],
  data?: PatchV1DevelopersIdMutationRequest,
  config: Partial<RequestConfig<PatchV1DevelopersIdMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchV1DevelopersIdMutationResponse,
    ResponseErrorConfig<PatchV1DevelopersId400 | PatchV1DevelopersId404>,
    PatchV1DevelopersIdMutationRequest
  >({
    method: "PATCH",
    url: `/v1/developers/${id}`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function patchV1DevelopersIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PatchV1DevelopersIdMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = patchV1DevelopersIdMutationKey();
  return mutationOptions<
    PatchV1DevelopersIdMutationResponse,
    ResponseErrorConfig<PatchV1DevelopersId400 | PatchV1DevelopersId404>,
    {
      id: PatchV1DevelopersIdPathParams["id"];
      data?: PatchV1DevelopersIdMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return patchV1DevelopersId(id, data, config);
    },
  });
}

/**
 * {@link /v1/developers/:id}
 */
export function usePatchV1DevelopersId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchV1DevelopersIdMutationResponse,
      ResponseErrorConfig<PatchV1DevelopersId400 | PatchV1DevelopersId404>,
      {
        id: PatchV1DevelopersIdPathParams["id"];
        data?: PatchV1DevelopersIdMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PatchV1DevelopersIdMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? patchV1DevelopersIdMutationKey();

  const baseOptions = patchV1DevelopersIdMutationOptions(
    config,
  ) as UseMutationOptions<
    PatchV1DevelopersIdMutationResponse,
    ResponseErrorConfig<PatchV1DevelopersId400 | PatchV1DevelopersId404>,
    {
      id: PatchV1DevelopersIdPathParams["id"];
      data?: PatchV1DevelopersIdMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PatchV1DevelopersIdMutationResponse,
    ResponseErrorConfig<PatchV1DevelopersId400 | PatchV1DevelopersId404>,
    {
      id: PatchV1DevelopersIdPathParams["id"];
      data?: PatchV1DevelopersIdMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PatchV1DevelopersIdMutationResponse,
    ResponseErrorConfig<PatchV1DevelopersId400 | PatchV1DevelopersId404>,
    {
      id: PatchV1DevelopersIdPathParams["id"];
      data?: PatchV1DevelopersIdMutationRequest;
    },
    TContext
  >;
}
