/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@oxlayer/api-client/client";
import type {
  PatchV1LicensesIdMutationRequest,
  PatchV1LicensesIdMutationResponse,
  PatchV1LicensesIdPathParams,
  PatchV1LicensesId400,
  PatchV1LicensesId404,
} from "../gen/PatchV1LicensesId.ts";
import type {
  RequestConfig,
  ResponseErrorConfig,
} from "@oxlayer/api-client/client";
import type {
  UseMutationOptions,
  UseMutationResult,
  QueryClient,
} from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const patchV1LicensesIdMutationKey = () =>
  [{ url: "/v1/licenses/:id" }] as const;

export type PatchV1LicensesIdMutationKey = ReturnType<
  typeof patchV1LicensesIdMutationKey
>;

/**
 * {@link /v1/licenses/:id}
 */
export async function patchV1LicensesId(
  id: PatchV1LicensesIdPathParams["id"],
  data?: PatchV1LicensesIdMutationRequest,
  config: Partial<RequestConfig<PatchV1LicensesIdMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const requestData = data;

  const res = await request<
    PatchV1LicensesIdMutationResponse,
    ResponseErrorConfig<PatchV1LicensesId400 | PatchV1LicensesId404>,
    PatchV1LicensesIdMutationRequest
  >({
    method: "PATCH",
    url: `/v1/licenses/${id}`,
    data: requestData,
    ...requestConfig,
  });
  return res.data;
}

export function patchV1LicensesIdMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<PatchV1LicensesIdMutationRequest>> & {
    client?: typeof fetch;
  } = {},
) {
  const mutationKey = patchV1LicensesIdMutationKey();
  return mutationOptions<
    PatchV1LicensesIdMutationResponse,
    ResponseErrorConfig<PatchV1LicensesId400 | PatchV1LicensesId404>,
    {
      id: PatchV1LicensesIdPathParams["id"];
      data?: PatchV1LicensesIdMutationRequest;
    },
    TContext
  >({
    mutationKey,
    mutationFn: async ({ id, data }) => {
      return patchV1LicensesId(id, data, config);
    },
  });
}

/**
 * {@link /v1/licenses/:id}
 */
export function usePatchV1LicensesId<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PatchV1LicensesIdMutationResponse,
      ResponseErrorConfig<PatchV1LicensesId400 | PatchV1LicensesId404>,
      {
        id: PatchV1LicensesIdPathParams["id"];
        data?: PatchV1LicensesIdMutationRequest;
      },
      TContext
    > & { client?: QueryClient };
    client?: Partial<RequestConfig<PatchV1LicensesIdMutationRequest>> & {
      client?: typeof fetch;
    };
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey =
    mutationOptions.mutationKey ?? patchV1LicensesIdMutationKey();

  const baseOptions = patchV1LicensesIdMutationOptions(
    config,
  ) as UseMutationOptions<
    PatchV1LicensesIdMutationResponse,
    ResponseErrorConfig<PatchV1LicensesId400 | PatchV1LicensesId404>,
    {
      id: PatchV1LicensesIdPathParams["id"];
      data?: PatchV1LicensesIdMutationRequest;
    },
    TContext
  >;

  return useMutation<
    PatchV1LicensesIdMutationResponse,
    ResponseErrorConfig<PatchV1LicensesId400 | PatchV1LicensesId404>,
    {
      id: PatchV1LicensesIdPathParams["id"];
      data?: PatchV1LicensesIdMutationRequest;
    },
    TContext
  >(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<
    PatchV1LicensesIdMutationResponse,
    ResponseErrorConfig<PatchV1LicensesId400 | PatchV1LicensesId404>,
    {
      id: PatchV1LicensesIdPathParams["id"];
      data?: PatchV1LicensesIdMutationRequest;
    },
    TContext
  >;
}
