/**
 * Create Delivery Man Use Case
 */

import { CreateUseCaseTemplate } from '@oxlayer/snippets/use-cases';
import type { AppResult } from '@oxlayer/snippets/use-cases';
import { DeliveryManRepository } from '@/repositories/index.js';
import { EventBus } from '@oxlayer/capabilities-events';
import { DeliveryManEntity, DeliveryManCreatedEvent } from '@/domain/index.js';

export interface CreateDeliveryManInput {
  name: string;
  email: string;
  password: string;
  phone: string;
  establishmentId?: number;
}

export interface CreateDeliveryManOutput {
  id: number;
  name: string;
  email: string;
  phone: string;
  isActive: boolean;
  createdAt: Date;
}

export class CreateDeliveryManUseCase extends CreateUseCaseTemplate<
  CreateDeliveryManInput,
  DeliveryManEntity,
  AppResult<CreateDeliveryManOutput>
> {
  constructor(
    private deliveryManRepository: DeliveryManRepository,
    eventBus: EventBus,
    tracer?: unknown | null
  ) {
    super({
      generateId: () => 0, // ID will be generated by database
      createEntity: (data) => DeliveryManEntity.create(data),
      persistEntity: async (entity) => {
        return await deliveryManRepository.create(entity);
      },
      publishEvent: async (event) => {
        try {
          await eventBus.emit(event);
        } catch (error) {
          console.warn('Failed to publish event:', error);
        }
      },
      toOutput: (entity) => ({
        id: entity.id,
        name: entity.name,
        email: entity.email,
        phone: entity.phone,
        isActive: entity.isActive,
        createdAt: entity.createdAt,
      }),
      tracer,
    });
  }

  protected override createEvent(entity: DeliveryManEntity, _id: number): DeliveryManCreatedEvent {
    return new DeliveryManCreatedEvent(entity.id, {
      email: entity.email,
      name: entity.name,
    });
  }
}
