/**
 * Create Service Provider Use Case
 */

import { CreateUseCaseTemplate } from '@oxlayer/snippets/use-cases';
import { ServiceProviderRepository } from '@/repositories/index.js';
import { EventBus } from '@oxlayer/capabilities-events';
import { ServiceProviderEntity, ServiceProviderCreatedEvent } from '@/domain/index.js';

export interface CreateServiceProviderInput {
  name: string;
  email: string;
  password: string;
  phone: string;
  categoryId: number;
  document: string;
  address: string;
  city: string;
  state: string;
  zipCode: string;
  available?: boolean;
  rating?: number;
}

export interface CreateServiceProviderOutput {
  id: number;
  name: string;
  email: string;
  phone: string;
  categoryId: number;
  isActive: boolean;
  createdAt: Date;
}

export class CreateServiceProviderUseCase extends CreateUseCaseTemplate<
  CreateServiceProviderInput,
  ServiceProviderEntity,
  Promise<CreateServiceProviderOutput>
> {
  constructor(
    private serviceProviderRepository: ServiceProviderRepository,
    eventBus: EventBus,
    tracer?: unknown | null
  ) {
    super({
      generateId: () => 0, // ID will be generated by database
      createEntity: (data) => ServiceProviderEntity.create(data),
      persistEntity: async (entity) => {
        return await serviceProviderRepository.create(entity);
      },
      publishEvent: async (event) => {
        try {
          await eventBus.emit(event);
        } catch (error) {
          console.warn('Failed to publish event:', error);
        }
      },
      toOutput: (entity) => ({
        id: entity.id,
        name: entity.name,
        email: entity.email,
        phone: entity.phone,
        categoryId: entity.categoryId!,
        isActive: entity.isActive,
        createdAt: entity.createdAt,
      }),
      tracer,
    });
  }

  protected override createEvent(entity: ServiceProviderEntity, _id: number): ServiceProviderCreatedEvent {
    return new ServiceProviderCreatedEvent(entity.id, {
      email: entity.email,
      name: entity.name,
    });
  }
}
